### ISSUE TITLE
[BUG] dh5view display scaling not working/robust with latest xyztc branch merge

### ISSUE THREAD

**Issue by csoeller** [python-microscopy/python-microscopy#1027]
**Describe the bug**

With the xyztc branch (now merged as #1016) something is definitely amiss with display scaling, at least in edge cases. Not sure if my image is an edge case but scaling is unusable in my hands.

**To Reproduce**
1. Open specific visgui generated TIFF with dh5view (I will supply link to image separately)
2. Try to scale display either using `Stretch` or `M` in histogram panel
3. Look at completely saturated display

**Expected behavior**
Prior to #1016 this worked okish.

**Screenshots**

Scaling with #1016:

<img width="912" alt="Screenshot 2021-05-07 at 20 27 38" src="https://user-images.githubusercontent.com/3750860/117504906-17332c80-af7b-11eb-856a-9164501ef258.png">

Scaling prior to #1016:

<img width="912" alt="Screenshot 2021-05-07 at 20 25 48" src="https://user-images.githubusercontent.com/3750860/117504984-33cf6480-af7b-11eb-8dd4-076d117ed675.png">

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
- python-microscopy=21.03.10
- python=3.7.6, platform=darwin
- numpy=1.19.2, wx=4.0.4 osx-cocoa (phoenix) wxWidgets 3.0.5

**Comment by David-Baddeley** [comment]
As a temporary workaround, click in the centre of the image and then try scaling. The issue is that the scaling is now calculated based on a ROI around the current selected position (which defaults to (0,0) when opening an image.

**Comment by csoeller** [comment]
Ok, sort of works but depending where I click (e.g. region with little staining) still blows up. Something more robust would eventually be nice (or make ROI big by default) - not sure the average user would know what is going on. See examples below:

<img width="912" alt="Screenshot 2021-05-07 at 21 40 02" src="https://user-images.githubusercontent.com/3750860/117506229-274c0b80-af7d-11eb-93cd-c1cbf51e5058.png">

<img width="912" alt="Screenshot 2021-05-07 at 21 40 09" src="https://user-images.githubusercontent.com/3750860/117506253-303cdd00-af7d-11eb-8630-12ac5d71c819.png">

**Comment by David-Baddeley** [comment]
Note, there will still be times when the subsampling makes the display scaling a little off for sparse data.
