### ISSUE TITLE
[BUG] Import stack order message confusing

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#1043]
**Describe the bug**
Super minor. Not 100% sure this is a bug. I have a .tif that is XYIZTC. I wanted to move the I to C and drop the I entirely. I opened the TIF in Fiji, ran "Image>Stacks>Stack To Images". Then I went to "Image > Color > Merge Channels" and I merged the 6 images into 6 color channels. Opening it in a Jupyter notebook with `im = ImageStack(filename=fn)`, it correctly identifies 6 color channels and then loads the stack.

```
(6, 2048, 2048)
Detected OME TIFF
sh = {'Z': 1, 'T': 1, 'C': 6, 'Y': 2048, 'X': 2048}
axisOrder =  XYCZT
[2048, 2048, 1, 1, 6]
```

I can still access everything as `im.data_xyztc` as expected. So, clearly `[2048, 2048, 1, 1, 6]` is the `im.data_xyztc` order, but the way the info is presented makes the user (or at least me) assume this order corresponds to `XYCZT` (i.e. it looks like `T` has 6 channels rather than `C`).

P.S. I need a GUI enabled to call  `im = ImageStack(filename=fn)` in a Jupyter notebook, because that dialog asking for voxel size pops up. Is there a way to just pass the voxel size and bypass the dialog?

**Comment by David-Baddeley** [comment]
With #1048, example data now loads. Can re-order dimensions in GUI as follows:

`Modules->redimension`, `Processing->Redimension`.

TODO - change `haveGUI` default in `ImageStack`
