### ISSUE TITLE
[BUG] Problem saving file paths on Windows with `update_yaml_keys()`

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#1045]
**Describe the bug**
`update_yaml_keys()` writes "\\\\" as "\\", and then yaml.safe_load loads this as "\\". As such, file paths on Windows become a problem when we store them in a configuration YAML. If I save a path to my file as written, it will load improperly the next time (i.e. ``C:\\\\path\\\\to\\\\my\\\\file" saves as "C:\\path\\to\\my\\file", loads as "C:\\path\\to\\my\\file"). Workaround is to swap "\\" for "\\\\" when saving file path to YAML. Generally swapping "\\\\" for "\\\\\\\\" in `update_yaml_keys()` feels a bit unsafe, though. Is there a better way to work around this problem?

Edit: I had to redo the backslashes in this GitHub editor so you could actually see what I mean. Same problem I'm describing in our code is happening here. Hah.

**Comment by David-Baddeley** [comment]
see http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html for a good rundown of yaml string quoting options
