### ISSUE TITLE
[ENHANCEMENT] Make it easier to move through color channels in `pymeimage`

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#1054]
I have some 6-channel images. In order to view each channel individually, I have to expand the window to maximum size and uncheck each channel I don't want to see. If I have more than 6 channels, I think I would be out of luck.

Two potential solutions come to mind:

- Make the Display Settings scrollable
- Allow attachment of a PlayPanel for color channels (maybe under modules? loaded by default?)

![image](https://user-images.githubusercontent.com/1263313/120668146-2e6f1800-c45c-11eb-90eb-45fb3fa65aaa.png)

**Comment by David-Baddeley** [comment]
Had a quick go at making it scroll when I did the import fixes and redimension dialog as I ran into similar issues with one of your example OIDIC images. Couldn't get vertical scrolling to play nice with the horizontal sizing in the ammount of time I had. Most of the scrolling code is still in there, albeit commented out until it could be revisited.

Scrolling through colours would require quite a different view philosophy (akin to imagej multichannel vs composite) and might be a bit tricky to implement and/or require substantial viewer mods.

I'll throw another couple of options out there:
- a "concertina" as used for layers in pymevis
- making the channel controls tabbed when the number of channels exceeds the vertical space
- putting the controls into a wrap sizer so you could resize horizontally to get them displayed in two columns

**Comment by David-Baddeley** [comment]
I think we can close this now ...
