### ISSUE TITLE
[BUG] Recipe modules don't read incident data source information on initial add

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#1057]
I press add module and I'll add, e.g., a `FilterTable`, and then select my input data source. If then right-click and Add a Filter, no keys are available.

![image](https://user-images.githubusercontent.com/1263313/121082740-884d4600-c7ac-11eb-94e9-678c42c4dbbc.png)

If I press "OK" and close the `FilterTable` and then double-click it again, now the keys populate.

![image](https://user-images.githubusercontent.com/1263313/121082815-a7e46e80-c7ac-11eb-802d-286078c6206f.png)

I'd like them to populate when I select the input data source the first time.

**Comment by David-Baddeley** [comment]
This is because the data source for the filter editor is set at creation time (see the `dataSource` parameter in custom_traits_editors.py L 84).  The FilterPanel can also take a callable which returns the datasource, which means that a solution like this might work:

`dataSource = lambda : self.factory.datasource`

**Comment by David-Baddeley** [comment]
key is to delay the datasource access to when the `filterPanel` calls `dataSource()`

**Comment by David-Baddeley** [comment]
unfortunately the above doesn't work. Neither does `dataSource = lambda : getattr(self.factory, 'datasource')`

**Comment by David-Baddeley** [comment]
Getting warmer, but not with an obvious solution - The core problem is that the editor updates the input datasource when it closes - hence the input is not defined until things have closed.
