### ISSUE TITLE
[BUG] point set generation - image.openImages not in name space, missing import

### ISSUE THREAD

**Issue by csoeller** [python-microscopy/python-microscopy#1068]
**Describe the bug**

**To Reproduce**
1. Configure point generation with image source
2. Generate fluorophore positions and events

**Expected behavior**
Just do as told.

**Screenshots**
N/A

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
- python-microscopy=21.03.10
- python=3.7.6, platform=darwin
- numpy=1.19.2, wx=4.0.4 osx-cocoa (phoenix) wxWidgets 3.0.5

**Error message**

```
 Error whilst running Extras>Synthetic Data>Generate fluorophore positions and events
==============================================
python-microscopy=21.03.10
python=3.7.6, platform=darwin
numpy=1.19.2, wx=4.0.4 osx-cocoa (phoenix) wxWidgets 3.0.5

Traceback
=========
Traceback (most recent call last):
  File "/Users/csoe002/Documents/src/PYME-src/pyme-py3/PYME/ui/progress.py", line 121, in func
    return fcn(*args, **kwargs)
  File "/Users/csoe002/Documents/src/PYME-src/pyme-py3/PYME/LMVis/Extras/pointSetGeneration.py", line 138, in OnGenPoints
    self.OnGenEvents(None)
  File "/Users/csoe002/Documents/src/PYME-src/pyme-py3/PYME/LMVis/Extras/pointSetGeneration.py", line 170, in OnGenEvents
    pipeline.imageBounds = image.openImages[self.source.image].imgBounds
NameError: name 'image' is not defined

```

**Comment by David-Baddeley** [comment]
Can we call this fixed?

**Comment by csoeller** [comment]
When you put back the `ed._values_changed()` check back in you check for a `ValueError` while the actual error raised is a `TypeError`. Therefore the current committed and merged code still does not work. Can you change the code as shown below? I believe after that we can close the issue.

In addition, I run into OpenGL errors when points are generated in an empty `visGUI`. This is not an issue if you generate the points in a `visGUI` instance that already shows events prior to generating the synthetic data. I probably better raise a separate issue for that?

<img width="1364" alt="Screenshot 2021-06-22 at 06 59 49" src="https://user-images.githubusercontent.com/3750860/122871953-a7f57a00-d327-11eb-902c-9b85b84761e6.png">

**Comment by David-Baddeley** [comment]
Sorry, I thought I'd done a 1:1 revert, but have been a bit distracted with a Marsden submission.

**Comment by csoeller** [comment]
No worries, fully understandable. I suggest I close this as soon as we have the fix in and I had a chance to test briefly.
