### ISSUE TITLE
[ENHANCEMENT] Change how we pass camera noise properties

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#1083]
Reproducing @David-Baddeley 's suggestion from closed PRs #144 and #1079. We can finish the discussion here and tick this off.

> My proposal:
> - we modify the base camera class to specify that all cameras should implement a .noise_properties property that returns a dictionary of the current properties
> - we modify the __init__() signature of the camera class to accept a noise_info parameter which can either be a path to a .yaml file (preferred), or a dictionary. The resulting noise_info dictionary must be keyed on the camera serial number (this should help avoid problems when swapping cameras), but what sits under that is up to the individual camera.
> - we make the above parameter optional, with cameras using either a PYME.config option to specify the location of the .yaml file, or a fixed location within the pyme config tree by default (this allows, amongst other things, a smooth upgrade path by transferring the current hard-coded properties to a .yaml that we distribute with PYME).
> - The use of a path to a .yaml allows a master file to be held on shared storage, if desired, making camera swaps etc ... easy.

It looks like `.noise_properties` is already included in the camera base class, and the return value suggests we implement this property in a derived class. I think everything described in @David-Baddeley's suggestion is common to all cameras, and I suggest we put all of the filename passing/YAML loading logic for noise properties in the camera base class, rather than re-implement it for each camera. We can simply default to `noise_info=None` and pass that information in specific cameras when necessary. Does this sound reasonable?

**Comment by David-Baddeley** [comment]
Can probably close this now with #1131
