### ISSUE TITLE
[BUG] pointsets FileSource issues: fileselector in save mode and np.load implementation issues for py3

### ISSUE THREAD

**Issue by csoeller** [python-microscopy/python-microscopy#1089]
**Describe the bug**
When configuring the `FileSource` the file dialog that comes up is a save dialog where it should be an open dialog. Also, loading 3 numpy arrays via a single `np.load` call seems not compatible with py3.

**To Reproduce**
1. in `LMVis` Go to `Extras>Synthetic Data>Configure`
2. Try to configure FileSource
3. Try to load from FileSource
4. points 2 and 3 have issues

   - Issue in point 2: a save dialog comes up that asks if a file should be overwritten or not.
   - Issue in point 3: get an error as np.load semantics have changed in py3

**Suggestions how to fix**

 - for point 2 add options to `File` trait, using the `exists=True` option e.g.

```patch
--- a/PYME/simulation/pointsets.py
+++ b/PYME/simulation/pointsets.py
@@ -30,13 +30,15 @@ class WormlikeSource(PointSource):
         mdh['GeneratedPoints.Source.PersistLength'] = self.persistLength
         
 class FileSource(PointSource):
-    file = File()
+    file = File(filter=['*.csv'],exists=True)
```

- for point 3 change to a more portable/versatile format, I suggest csv:

```patch
     def getPoints(self):
-        import numpy as np
-        return np.load(self.file)
+        # switched to csv based storage format
+        import pandas as pd
+        df = pd.read_csv(self.file)
+        return (df['x'].values,df['y'].values,df['z'].values)
 
     def genMetaData(self, mdh):
         mdh['GeneratedPoints.Source.Type'] = 'File'
```

I will prepare a PR with these points, the details of the coordinate format can be discussed. I will also suggest a `Extras>Synthetic Data>Save fluorophore positions` menu entry as saving generated positions can be very useful for the analysis of simulated data and allows reloading of the same positions at a later stage.

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
- python-microscopy=21.07.07
- python=3.7.6, platform=darwin
- numpy=1.19.2, wx=4.0.4 osx-cocoa (phoenix) wxWidgets 3.0.5

**Comment by David-Baddeley** [comment]
Guessing we should be able to close with #1090
