### ISSUE TITLE
[BUG] `pymeacquire` simulation settings don't display until window is resized

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#1094]
```
Traceback (most recent call last):
  File "/Users/zachcm/Code/python-microscopy/PYME/Acquire/acquiremainframe.py", line 238, in doPostInit
    cm.run(self, self.scope)
  File "/Users/zachcm/Code/python-microscopy/PYME/Acquire/ExecTools.py", line 205, in run
    self.codeObj(parent, scope)
  File "/Users/zachcm/Code/python-microscopy/PYME/Acquire/Scripts/init.py", line 120, in fake_dmd
    from PYMEnf.Hardware import FakeDMD, DMDGui
ModuleNotFoundError: No module named 'PYMEnf'
```

This seems to result in an inability to display/use Simulation Settings on both Mac and Windows.

![image](https://user-images.githubusercontent.com/1263313/127501801-6b13afd9-3ac9-447d-8a6e-5fe09a612534.png)

**Comment by zacsimile** [comment]
Ugh, just kidding. These are two separate errors. The `PYMEnf` error isn't actually a problem. We could consider commenting out `PYMEnf` calls by default in the main repo so as to not have to consider irrelevant errors.

The display doesn't work until you resize the window, then it works fine.

![image](https://user-images.githubusercontent.com/1263313/127502441-a0682ed7-6ac0-4516-876f-4ffd97ad066f.png)

This is a problem on `wx 4.0.4` and `wx 4.1.1`.

**Comment by zacsimile** [comment]
It seems like the easiest thing to do is bind `PYME.ui.manualFoldingPanel.foldPanel.fold1` to `SetSelection()`. Not sure why this isn't bound/exactly how to bind it.

**Comment by David-Baddeley** [comment]
Or maybe bind to a resize, rather than `SetSelection()` specifically. 

I swear this is new - maybe a regression from the work on the dh5view colour channels which involved subtle tweaks to the folding panes etc ... to make them do sensible things when resized.

**Comment by David-Baddeley** [comment]
I'm guessing the underlying problem is something along the following lines:

- window gets created hidden with 0 size
- because tab is inactive, all layout is done with 0 size
- this doesn't refresh when changing to that tab (until the whole window is resized)
