### ISSUE TITLE
[BUG] automated builds folder empty?

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#1120]
Links/etc were working on Thursday morning Pacific time, by the evening It looked as it does below, which is what I'm still seeing now.

https://python-microscopy.org/downloads/automated_builds/
<img width="576" alt="Screen Shot 2021-09-18 at 10 46 27 AM" src="https://user-images.githubusercontent.com/31105780/133897824-731b30de-a58c-4dfa-9309-4b7ced798001.png">

Note that https://python-microscopy.org/downloads, and https://python-microscopy.org/downloads/old_versions are still looking good.

Also, would be nice to link the automated_builds page from the downloads page as we do for old versions

**Comment by David-Baddeley** [comment]
The most recent automated build is now in downloads, so I cleared out the
automated builds.

Intent of automated builds was as a stageing area... Gets dropped in
automated builds by the build scripts, gets tested, gets moved to
downloads. The initial goal was to only ever have things stay in automated
builds for a day or two, before being moved to downloads.

We could revisit if/when we move to regular fully automated builds.
