### ISSUE TITLE
[BUG] Measure Objects appears to be broken

### ISSUE THREAD

**Issue by lukasfue** [python-microscopy/python-microscopy#1121]
I generated a jittered triangulation image, thresholded it, labeled it, and used "Get Segmented IDs from labeled image". Then I tried to "measure objects" and received the following traceback:

 Error whilst running Analysis>Measure objects
==============================================
python-microscopy=21.09.16.post0
python=3.7.9, platform=win32
numpy=1.19.1, wx=4.0.4 msw (phoenix) wxWidgets 3.0.5

Traceback
=========
Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\ui\progress.py", line 153, in func
    return fcn(*args, **kwargs)
  File "c:\users\laf62\python-microscopy\PYME\LMVis\Extras\objectMeasurements.py", line 149, in OnMeasure
    dlg = OMDialog(pipeline.keys())
  File "c:\users\laf62\python-microscopy\PYME\LMVis\Extras\objectMeasurements.py", line 61, in __init__
    self.SetSizerAndFit(vsizer)
wx._core.wxAssertionError: C++ assertion "((HWND)GetHWND())" failed at ..\..\src\msw\window.cpp(1162) in wxWindow::GetLayoutDirection(): invalid window

This approach definitely worked before, so I'm not sure what the issue is.

**Comment by zacsimile** [comment]
Hmm I tried DBSCAN and then analysis > measure objects on a mac and got a straight segfault...

**Comment by zacsimile** [comment]
This appears to be the line causing the segfault

```
hsizer.Add(wx.StaticText(self, -1, 'Label column:'), 0, wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 2)
```

Very confused. I am also on wxpython=4.0.4.

**Comment by David-Baddeley** [comment]
hmm, definitely confusing ... I suspect that this and Zach's errors are unrelated, but can't be sure.

@lukasfue - is it possible that that there is more to that traceback / an earlier traceback that can be seen in the console? I can't see any obvious reason why you should be getting that traceback.

**Comment by zacsimile** [comment]
I ran it on Windows and this is my traceback

```
SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set                                  Traceback (most recent call last):                                                                                        File "c:\users\zrc4\code\python-microscopy\PYME\ui\manualFoldPanel.py", line 759, in OnResize                             if (not self._in_fold1) and self.IsShownOnScreen():                                                                 RuntimeError: wrapped C/C++ object of type foldPanel has been deleted  
```

**Comment by zacsimile** [comment]
I get the same error as @lukasfue on my windows 10 machine. No additional info.

**Comment by lukasfue** [comment]
Here is the entire output from running visgui (note sure if this is helpful or not)

`(pyme) C:\Users\laf62>visgui
Trying to load 3rd party recipe module pyme_4pi.recipe_modules.conversion
Loaded 3rd party recipe module pyme_4pi.recipe_modules.conversion
Trying to load 3rd party recipe module ch_shrinkwrap.recipe_modules.surface_fitting
Loaded 3rd party recipe module ch_shrinkwrap.recipe_modules.surface_fitting
Trying to load 3rd party recipe module cc_drift_cor.plugins.recipes.io
Loaded 3rd party recipe module cc_drift_cor.plugins.recipes.io
Trying to load 3rd party recipe module cc_drift_cor.plugins.recipes.chung_cc
Loaded 3rd party recipe module cc_drift_cor.plugins.recipes.chung_cc
Trying to load 3rd party recipe module cc_drift_cor.plugins.recipes.processing
Loaded 3rd party recipe module cc_drift_cor.plugins.recipes.processing
Trying to load 3rd party recipe module nep_fitting.recipe_modules.nep_fits
Loaded 3rd party recipe module nep_fitting.recipe_modules.nep_fits
Trying to load 3rd party recipe module cc_drift_cor.plugins.recipes.localisations
Loaded 3rd party recipe module cc_drift_cor.plugins.recipes.localisations
INFO:OpenGL.GLUT.special:Using NT-specific GLUT calls with exit callbacks
quaternion module not found, disabling custom clip plane orientations
quaternion module not found, disabling custom clip plane orientations
New Canvas
DEBUG:PYME.LMVis.visCore:Creating VisGUI menu bar
DEBUG:PYME.LMVis.Extras:Initializing QPobjectSegment plugin
DEBUG:PYME.LMVis.Extras:Initializing animation plugin
DEBUG:PYME.LMVis.Extras:Initializing clusterAnalysis plugin
DEBUG:PYME.LMVis.Extras:Initializing dockedPanel plugin
DEBUG:PYME.LMVis.Extras:Initializing extra_layers plugin
DEBUG:PYME.LMVis.Extras:Initializing fiducial plugin
DEBUG:PYME.LMVis.Extras:Initializing flagZMotionArtifacts plugin
DEBUG:root:Adding menu items for event filters
DEBUG:PYME.LMVis.Extras:Initializing fusionUtils plugin
DEBUG:PYME.LMVis.Extras:Initializing multiColourAnalysis plugin
DEBUG:PYME.LMVis.Extras:Initializing multiviewMapping plugin
DEBUG:root:Adding menu items for multi-view manipulation
DEBUG:PYME.LMVis.Extras:Initializing objectMeasurements plugin
DEBUG:PYME.LMVis.Extras:Initializing particleTracking plugin
DEBUG:PYME.LMVis.Extras:Initializing perFrameVariable plugin
DEBUG:PYME.LMVis.Extras:Initializing photophysics plugin
DEBUG:PYME.LMVis.Extras:Initializing pointSetGeneration plugin
DEBUG:PYME.LMVis.Extras:Initializing pointwiseColoc plugin
DEBUG:PYME.LMVis.Extras:Initializing saved_views plugin
Saved Views are deprecated -  use the ones with animation instead and remove me!
DEBUG:PYME.LMVis.Extras:Initializing scaleBox plugin
DEBUG:PYME.LMVis.Extras:Initializing sequentialSpecies plugin
DEBUG:PYME.LMVis.Extras:Initializing setBGImage plugin
DEBUG:PYME.LMVis.Extras:Initializing shiftmapGenerator plugin
DEBUG:PYME.LMVis.Extras:Initializing showShortcuts plugin
DEBUG:PYME.LMVis.Extras:Initializing snapshot plugin
DEBUG:PYME.LMVis.Extras:Initializing spherical_harmonics plugin
DEBUG:root:Adding menu items for spherical harmonic (shell) fitting
DEBUG:PYME.LMVis.Extras:Initializing subsets plugin
DEBUG:PYME.LMVis.Extras:Initializing surface_fitting plugin
DEBUG:PYME.LMVis.Extras:Initializing temperaturePlot plugin
DEBUG:PYME.LMVis.Extras:Initializing vibration plugin
Creating fold panel
GenPanels
Creating datasource panel
RecipeView._layout
Input datasources:  []
Image list size: 1
Creating layers GUI
height:  0
NB best size: wx.Size(200, 0)
RecipeView._layout
Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\ui\manualFoldPanel.py", line 759, in OnResize
    if (not self._in_fold1) and self.IsShownOnScreen():
RuntimeError: wrapped C/C++ object of type foldPanel has been deleted
Input datasources:  []
recipe.execute()
RecipeView._layout
Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\ui\manualFoldPanel.py", line 759, in OnResize
    if (not self._in_fold1) and self.IsShownOnScreen():
RuntimeError: wrapped C/C++ object of type foldPanel has been deleted
Input datasources:  []
0
OpenGL - Version: b'4.6.0 NVIDIA 456.71'
Shader - Version: b'4.60 NVIDIA'
GL_MAX_SAMPLES: 32, GL_SAMPLES: 4
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.DefaultShaderProgram'>
Ev Idle
('points', 't')
refreshed
Creating Pipeline
RecipeView._layout
Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\ui\manualFoldPanel.py", line 759, in OnResize
    if (not self._in_fold1) and self.IsShownOnScreen():
RuntimeError: wrapped C/C++ object of type foldPanel has been deleted
Input datasources:  ['_Localizations', 'FitResults']
RecipeView._layout
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\ui\manualFoldPanel.py", line 759, in OnResize
    if (not self._in_fold1) and self.IsShownOnScreen():
RuntimeError: wrapped C/C++ object of type foldPanel has been deleted
Input datasources:  ['_Localizations', 'FitResults']
RecipeView._layout
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\ui\manualFoldPanel.py", line 759, in OnResize
    if (not self._in_fold1) and self.IsShownOnScreen():
RuntimeError: wrapped C/C++ object of type foldPanel has been deleted
Input datasources:  ['_Localizations', 'FitResults']
recipe.execute()
Executing <PYME.recipes.localisations.Pipelineify object at 0x00000224BD65BCA8>
DEBUG:PYME.recipes.localisations:no events found
WARNING:PYME.LMVis.pipeline:Spoofing focus from metadata: this usually implies an error in the input data (missing events) and results might vary
ERROR:PYME.LMVis.pipeline:Error trying to fudge focus positions
Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\experimental\labview_spooling_hacks.py", line 32, in spoof_focus_from_metadata
    assert mdh['StackSettings.StepSize'] > 0  # np.arange will fail with a step size of 0
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\LMVis\pipeline.py", line 285, in _processEvents
    position, frames = labview_spooling_hacks.spoof_focus_from_metadata(mdh)
  File "c:\users\laf62\python-microscopy\PYME\experimental\labview_spooling_hacks.py", line 46, in spoof_focus_from_metadata
    sys.exc_info()[2])
  File "C:\Users\laf62\.conda\envs\pyme\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "c:\users\laf62\python-microscopy\PYME\experimental\labview_spooling_hacks.py", line 32, in spoof_focus_from_metadata
    assert mdh['StackSettings.StepSize'] > 0  # np.arange will fail with a step size of 0
AssertionError: Error spoofing focus events -  frames: [0], positions None
Executing <PYME.recipes.localisations.ProcessColour object at 0x00000224C33DB1C8>
Executing <PYME.recipes.tablefilters.FilterTable object at 0x00000224C3C3EAC8>
RecipeView._layout
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\ui\manualFoldPanel.py", line 759, in OnResize
    if (not self._in_fold1) and self.IsShownOnScreen():
RuntimeError: wrapped C/C++ object of type foldPanel has been deleted
Input datasources:  ['_Localizations', 'FitResults']
WARNING:PYME.LMVis.pipeline:Spoofing focus from metadata: this usually implies an error in the input data (missing events) and results might vary
ERROR:PYME.LMVis.pipeline:Error trying to fudge focus positions
Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\experimental\labview_spooling_hacks.py", line 32, in spoof_focus_from_metadata
    assert mdh['StackSettings.StepSize'] > 0  # np.arange will fail with a step size of 0
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\LMVis\pipeline.py", line 285, in _processEvents
    position, frames = labview_spooling_hacks.spoof_focus_from_metadata(mdh)
  File "c:\users\laf62\python-microscopy\PYME\experimental\labview_spooling_hacks.py", line 46, in spoof_focus_from_metadata
    sys.exc_info()[2])
  File "C:\Users\laf62\.conda\envs\pyme\lib\site-packages\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "c:\users\laf62\python-microscopy\PYME\experimental\labview_spooling_hacks.py", line 32, in spoof_focus_from_metadata
    assert mdh['StackSettings.StepSize'] > 0  # np.arange will fail with a step size of 0
AssertionError: Error spoofing focus events -  frames: [0], positions None
Pipeline Created
RecipeView._layout
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\ui\manualFoldPanel.py", line 759, in OnResize
    if (not self._in_fold1) and self.IsShownOnScreen():
RuntimeError: wrapped C/C++ object of type foldPanel has been deleted
Input datasources:  ['_Localizations', 'FitResults']
DEBUG:PYME.LMVis.VisGUI:Creating tabs
0
DEBUG:PYME.LMVis.VisGUI:Finished creating tabs
Gui stuff done
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.OpaquePointShaderProgram'>
lw update
Creating layers GUI
hl update
height:  320
NB best size: wx.Size(222, 320)
DEBUG:PYME.LMVis.visCore:Added layer, datasouce=output
lw update
hl update
hl update
New Canvas
DEBUG:PYME.DSView.modules:visgui.Plug() took 0.05 s
WARNING:PYME.DSView.modules:Plugin [visgui] injects into dsviewer namespace, could result in circular references
DEBUG:PYME.DSView.modules:filtering.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:cropping.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:redimension.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:composite.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:profilePlotting.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:splitter.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:synchronise.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:coloc.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:vis3D.Plug() took 0.00 s
Creating fold panel
OpenGL - Version: b'4.6.0 NVIDIA 456.71'
Shader - Version: b'4.60 NVIDIA'
GL_MAX_SAMPLES: 32, GL_SAMPLES: 4
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.DefaultShaderProgram'>
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.ImageShaderProgram'>
lw update
c:\users\laf62\python-microscopy\PYME\LMVis\layers\image_layer.py:275: PYMEDeprecationWarning: This will either disappear or change function as we move to a 5D data model. Use the explicit .data_xytc instead, or even better, change to using the 5D model as image.data_xyztc or image.voxels
  self._im = ds.data[:,:,self.slice,self.channel].astype('f4').squeeze()# - c0)/(c1-c0)
lw update
(255, 4) [1. 1. 1. 1.]
lw update
lw update
lw update
c:\users\laf62\python-microscopy\PYME\DSView\modules\filtering.py:202: PYMEDeprecationWarning: This will either disappear or change function as we move to a 5D data model. Use the explicit .data_xytc instead, or even better, change to using the 5D model as image.data_xyztc or image.voxels
  filt_ims = [np.atleast_3d(self.image.data[:,:,:,chanNum].squeeze() > self.image.labelThresholds[chanNum]) for chanNum in range(self.image.data.shape[3])]
New Canvas
DEBUG:PYME.DSView.modules:visgui.Plug() took 0.05 s
WARNING:PYME.DSView.modules:Plugin [visgui] injects into dsviewer namespace, could result in circular references
DEBUG:PYME.DSView.modules:filtering.Plug() took 0.01 s
DEBUG:PYME.DSView.modules:cropping.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:redimension.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:composite.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:profilePlotting.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:splitter.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:synchronise.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:coloc.Plug() took 0.00 s
DEBUG:PYME.DSView.modules:vis3D.Plug() took 0.00 s
Creating fold panel
OpenGL - Version: b'4.6.0 NVIDIA 456.71'
Shader - Version: b'4.60 NVIDIA'
GL_MAX_SAMPLES: 32, GL_SAMPLES: 4
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.DefaultShaderProgram'>
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.ImageShaderProgram'>
lw update
(255, 4) [1. 1. 1. 1.]
recipe.execute()
Executing <PYME.recipes.localisations.LabelsFromImage object at 0x000002250360BE28>
c:\users\laf62\python-microscopy\PYME\Analysis\points\coordinate_tools.py:228: RuntimeWarning: invalid value encountered in true_divide
  z_index = np.floor((points['z'] - z0) / image.voxelsize_nm.z).astype('i') # no origin correction for point, as absolutely referenced.
c:\users\laf62\python-microscopy\PYME\Analysis\points\cluster_morphology.py:48: PYMEDeprecationWarning: This will either disappear or change function as we move to a 5D data model. Use the explicit .data_xytc instead, or even better, change to using the 5D model as image.data_xyztc or image.voxels
  label_data = label_image.data
lw update
hl update
RecipeView._layout
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\ui\manualFoldPanel.py", line 759, in OnResize
    if (not self._in_fold1) and self.IsShownOnScreen():
RuntimeError: wrapped C/C++ object of type foldPanel has been deleted
Input datasources:  ['_Localizations', 'FitResults', 'Labelled Image 0']
RecipeView._layout
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(478) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set
Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\ui\manualFoldPanel.py", line 759, in OnResize
    if (not self._in_fold1) and self.IsShownOnScreen():
RuntimeError: wrapped C/C++ object of type foldPanel has been deleted
Input datasources:  ['_Localizations', 'FitResults', 'Labelled Image 0']
lw update
hl update
Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\ui\progress.py", line 153, in func
    return fcn(*args, **kwargs)
  File "c:\users\laf62\python-microscopy\PYME\LMVis\Extras\objectMeasurements.py", line 149, in OnMeasure
    dlg = OMDialog(pipeline.keys())
  File "c:\users\laf62\python-microscopy\PYME\LMVis\Extras\objectMeasurements.py", line 61, in __init__
    self.SetSizerAndFit(vsizer)
wx._core.wxAssertionError: C++ assertion "((HWND)GetHWND())" failed at ..\..\src\msw\window.cpp(1162) in wxWindow::GetLayoutDirection(): invalid window`

**Comment by David-Baddeley** [comment]
I've got a possible candidate ...

I think `super().__init__(*args, **kwargs)` on line 28 of objectMeasurements.py should be `super().__init__(self, *args, **kwargs)`. Will have a test locally and see if I can replicate/fix (although don't currently have easy access to a windows machine for testing).

**Comment by David-Baddeley** [comment]
`super()` was not the issue, found a different issue which could be responsible, fixed in #1122. Will trigger another package build, but keep this open until verified to work on win10

**Comment by zacsimile** [comment]
This now works for me in Windows 10. @lukasfue ?

**Comment by David-Baddeley** [comment]
Going to call this fixed, feel free to reopen if not.
