### ISSUE TITLE
[BUG] `dh5view` File > Export Cropped not working as expected

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#1129]
I tried to export cropped a single z-slice, 2048x2048 image with 6 color channels. I received the following traceback. Even if each pixel was a double, I think this should still only be ~201 MB. Feels like maybe export cropped isn't working as expected.

![image](https://user-images.githubusercontent.com/1263313/137538274-06b4b093-a716-42c1-82eb-fb64d3b02d45.png)

```
 Error whilst running File>&Export Cropped
==============================================
python-microscopy=21.09.23
python=3.7.11, platform=win32
numpy=1.21.1, wx=4.0.7.post2 msw (phoenix) wxWidgets 3.0.5

Traceback
=========
Traceback (most recent call last):
  File "c:\users\zrc4\code\python-microscopy\PYME\ui\progress.py", line 153, in func
    return fcn(*args, **kwargs)
  File "c:\users\zrc4\code\python-microscopy\PYME\DSView\dsviewer.py", line 363, in OnExport
    self.image.Save(crop = True, roi=roi)
  File "c:\users\zrc4\code\python-microscopy\PYME\IO\image.py", line 1318, in Save
    dataExporter.CropExportData(self.data_xyztc, roi, self.mdh, self.events, self.seriesName)
  File "c:\users\zrc4\code\python-microscopy\PYME\IO\dataExporter.py", line 621, in CropExportData
    exp.Export(data, filename, dlg.GetXSlice(), dlg.GetYSlice(), dlg.GetZSlice(),mdh, events, origName)
  File "c:\users\zrc4\code\python-microscopy\PYME\IO\dataExporter.py", line 288, in Export
    raise RuntimeError('TIFF has a maximum file size of 4GB, crop data or save as HDF')
RuntimeError: TIFF has a maximum file size of 4GB, crop data or save as HDF
```

**Comment by David-Baddeley** [comment]
Super weird - did you manually enter the 75, 76? for the z slices?

**Comment by David-Baddeley** [comment]
We probably need to revisit the `CropExportData` for xyztc ...

**Comment by zacsimile** [comment]
Yes, I manually entered it.

**Comment by zacsimile** [comment]
Is it possible the error is in `Exporter._prepare()` in `PYME.IO.dataExporter.py`? It looks like it returns the original data (uncropped), but then the `OMETiffExporter` checks the `data` parameter to see how big the exported file should be and sees the original file size, then it saves the data.

**Comment by zacsimile** [comment]
Ah, I see in `H5Exporter` that the exporter takes care of reslicing the data to its cropped size. Presumably this is what we want to do in `OMETiffExporter` as well?

**Comment by David-Baddeley** [comment]
It would probably be cleaner to have `_prepare()` return a `PYME.IO.DataSources.CropDataSource` (or a suitably modified xyztc version thereof. It would put all the crop logic in one place, and lay the foundations for a crop recipe module which is also on the TODO list.

**Comment by David-Baddeley** [comment]
Would be a good chance to re-factor `PYME.DSView.modules.cropping` as well so that we have all our cropping logic in one place.
