### ISSUE TITLE
[BUG/ENHACEMENT] Frame doesn't change when I click on `dh5view` playback bar

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#1130]
Not sure if this is a bug or an enhancement. If I click anywhere on the dh5view playback bar, the frame number doesn't change, even though the slider position does. If I hit play, the slider goes back to where it was before and keeps running. GOTO changes the frame number just fine. I expect clicking somewhere on the play bar to have the same behavior as GOTO.

**Comment by David-Baddeley** [comment]
Which platform? It works as expected for me on mac.

**Comment by zacsimile** [comment]
Sorry--Windows 10.

**Comment by zacsimile** [comment]
Ok, funny, it works if I click+drag the slider position to a new frame, but not if I just click where I want to go along the slider.

**Comment by David-Baddeley** [comment]
I seem to recall that windows and mac generate slightly different scroll events. I suspect that the discrepancy is down to how we handle things - we try to only handle scroll end events (i.e. not the intermediate events generated while dragging the scroll bar) to avoid the unnecessary IO (and unacceptable performance) of loading lots intermediate frames as the user drags the scroll bar. I think this comes down to **not** handling `EVT_SCROLL`. It might be that just clicking a position on the scroll bar in windows generates an event we don't handle.

**Comment by David-Baddeley** [comment]
OK, looking at the code, we handle `EVT_SCROLL_THUMBRELEASE`, `EVT_SCROLL_LINEUP`, `EVT_SCROLL_LINEDOWN`

Adding `EVT_SCROLL_CHANGED` might fix this.

**Comment by David-Baddeley** [comment]
see https://wxpython.org/Phoenix/docs/html/wx.ScrollEvent.html

it's specifically the `EVT_SCROLL_THUMBTRACK` that get caught by `EVT_SCROLL` that we don't want.
