### ISSUE TITLE
[BUG] `dh5view` Processing > Crop does not crop color channels

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#1132]
It only returns an x/y/z crop, even when color channels are present. Perhaps related to #1129?

**Comment by David-Baddeley** [comment]
Unrelated to #1129, as it uses completely separate cropping logic (although we should potentially change this). Current behaviour (returns all colour channels in the cropped image) is correct and, i.m.o. most intuitive. Cropping is spatial truncation, and as a result doesn't easily extend to colour. This is true both in terms of user interface - you can't drag a colour selection - and in terms of logic. Cropping extracts a contiguous regions of pixels and this doesn't translate well to colour, where each channel is it's own discrete entity. You are not e.g. more likely to want channels 1 to 3 than, e.g. 1 and 5.  You can, however split channels using the separate split channels function, or choose a combination of channels to include in a new image with `make composite`.

**Comment by zacsimile** [comment]
Sorry, I phrased this poorly. It doesn't return all color channels, but rather only the one selected (at least on my Windows machine). I agree that returning all color channels makes the most sense.

**Comment by David-Baddeley** [comment]
What data is this running on? It always returns all channels for me.

**Comment by zacsimile** [comment]
Ok sorry I wasn't at the latest version. This crops all channels for me now.
