### ISSUE TITLE
[ENHANCEMENT] GUI toggle crosshairs and scalebar in PYMEImage

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#1153]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I need to render 16 images and for each one I have to execute two lines of code in the shell. I can do it, but others might not know the secret passwords

**Describe the solution you'd like**
1. leave the crosshairs off unless someone clicks the button on the side panel.
2. scalebar toggle/options more like in PYMEVis

**Comment by David-Baddeley** [comment]
looks like a duplicate of #876,

should now be fixed as of #1149 

![image](https://user-images.githubusercontent.com/19475296/143299621-88302495-d4f4-4c67-b333-101ee858ec97.png)

can discuss whether default mode on startup should show crosshairs or not, but there is now an easy way to toggle them in the GUI. Probably not quite as slick as the VisGUI toolbar toggling, but more versatile (as it also allows toggling other overlays - e.g. annotations, point selections, etc ...

**Comment by David-Baddeley** [comment]
![image](https://user-images.githubusercontent.com/19475296/143300566-606badf4-0da4-4cd5-a5b6-574eeac24bad.png)

**Comment by David-Baddeley** [comment]
@barentine - will close as already fixed unless you feel strongly about crosshairs on startup. Another consideration would be to disable them on export (although this needs a fair bit of special-case logic).

**Comment by barentine** [comment]
<img width="944" alt="Screen Shot 2022-02-09 at 3 24 18 PM" src="https://user-images.githubusercontent.com/31105780/153307583-efa1023c-972a-4c52-a92a-e5a79d3daa23.png">
Lost this behavior recently for h5
