### ISSUE TITLE
[BUG] newer skimage 0.19.x has new dtype option which trips up skfilters.py recipe autowrapper

### ISSUE THREAD

**Issue by csoeller** [python-microscopy/python-microscopy#1275]
**Describe the bug**
Latest `skimage.filters` (0.19.x) has a change in the gabor_kernel optional arguments that adds a `numpy`dtype which trips up the current autowrapper code.

**To Reproduce**
1. Open one of the PYME apps that import the `skimage` recipes, e.g. `dh5view`, `PYMEVis`etc
4. See error on import of skimage

```python
Could not import skimage

Traceback (most recent call last):

  File "/Users/csoe002/Documents/src/PYMEsrc/pyme38/PYME/recipes/modules.py", line 26, in <module>

    from . import skfilters

  File "/Users/csoe002/Documents/src/PYMEsrc/pyme38/PYME/recipes/skfilters.py", line 128, in <module>

    exec(cd)

  File "<string>", line 81

    dtype = _IntFloat(<class 'numpy.complex128'>)

                      ^

SyntaxError: invalid syntax
```

**Expected behavior**
Should import cleanly.

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
```
python-microscopy=22.05.25.post0.dev[git]80684a40bcad
python=3.8.13, platform=darwin
numpy=1.23.2, wx=4.2.0 osx-cocoa (phoenix) wxWidgets 3.2.0
```

**Comment by David-Baddeley** [comment]
should now be able to close
