### ISSUE TITLE
[BUG] Traitsui list editor causes hard crash (segfault)

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#1292]
**Describe the bug**
Any time you have a `List`, `ListFloat` etc .... trait in the view for a recipe module you will crash PYMEVis with a segfault (this appears to be in the vertical recipe display). Triggered by `localisations.DensityMapping`, with temporary **ugly** workaround in #1291.

This is really a traitsui and/or wx bug, but until that gets fixed we need to find a workaround.

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: Mac
 - Python version: 3.8
 - wxpython version [if a UI bug]: 4.1.1
 - traitsui: 7.1.0

**Comment by barentine** [comment]
Note that with 22.10.13 I no longer have the color channel list option:
![image](https://user-images.githubusercontent.com/31105780/196251230-58567d0d-55d8-417f-aaee-c54470bbd596.png)
so even if I pass a `ProcessColour`ed tabular through with channels [chan0, chan1] I get a single-channel histogram out (unless tif saving has regressed and is only saving a single channel)

**Comment by David-Baddeley** [comment]
Definitely need to look at this again - had naively thought that the behaviour with defaults would be the same as with the GUI route and that you'd get a 2-colour image if you didn't specify anything with the channels.

Can potentially manually specify a non-crashing editor in the view ... or might go away with more recent traitsui/pyface

**Comment by David-Baddeley** [comment]
Workaround is to specify in the recipe text, but that's a bit gross ...
