### ISSUE TITLE
[BUG] First layer in two-color datasets has no tab for editing but the data is still visualized

### ISSUE THREAD

**Issue by lukasfue** [python-microscopy/python-microscopy#1299]
**Describe the bug**
Typically, when two-color data is loaded, it starts with three layers. The first layer contains all data, the second layer contains color channel 1 data, and the third layer contains color channel 2 data. Currently, on the master branch of python-microscopy, the first layer's tab is missing but the data is still displayed. This means the data is visualized but it cannot be edited or turned off/on. 

**To Reproduce**
1. Load two-color dataset
2. See that all data is displayed but no tab is present to edit it or turn it off

**Expected behavior**
The tab is present to allow editing

**Screenshots**
![image](https://user-images.githubusercontent.com/36608397/195640202-6ae8522f-a1ce-4202-a43d-f953430a8ade.png)
Note that he visualize 'eyes' are off on both layers, but data is still displayed.

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: Windows 10
 - Python version: 3.7.9
 - numpy version: 1.19.1
 - wxpython version [if a UI bug]: 4.0.4

**Comment by David-Baddeley** [comment]
Almost certainly related to #1300 .... 

Note that a 2 colour data set typically has 3 layers (the 2 colours and a combined layer with all localisations). It is this 3rd layer that you are seeing, but the layer controls haven't been added.

This was probably introduced with #1294, as a side effect to an effort to clobber a bunch of wxAssertion errors that were showing up on the command line.
