### ISSUE TITLE
[BUG] Error when open PYMEAcquire

### ISSUE THREAD

**Issue by Yujin-Bao** [python-microscopy/python-microscopy#1319]
**Describe the bug**
`ImportError` when opening `PYMEAcquire`. It seems it is due to the last commit of `displaySettingsPanel.py`, which is "make histogram background change colour on saturation".

**To Reproduce**
Open `PYMEAcquire` (with PCO camera) and you will see the error and traceback.

**Screenshots**
![image](https://user-images.githubusercontent.com/80548133/205413031-4d10eab3-9021-4f80-a56e-70909319b070.png)

**Comment by barentine** [comment]
Hi @Yujin-Bao , am I correct that this is a development install and you didn't rerun `python setup.py develop` after updating? Give that a try and let us know if that fixes things

**Comment by Yujin-Bao** [comment]
Hi @barentine, thanks for the hint! It works after I reran python `setup.py develop`!

**Comment by barentine** [comment]
Great! Feel free to close the issue then. Thanks

**Comment by David-Baddeley** [comment]
Think we can close this as resolved, but make a mental not that there should be some way of indicating when a rebuild is needed for source installs (safest is to assume it always is - do the docs reflect this?)
