### ISSUE TITLE
[PROPOSAL] IDS Peak API version of ueye / ucam camera classes

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#1321]
**Is your feature request related to a problem? Please describe.**
IDS has deprecated their UI cameras, e.g. IDS-UI-3240ML-NIR-GL, and their new U3 cameras run on IDSPeak. More info [here](https://www.1stvision.com/cameras/IDS-imaging-software).

Note that uEye (UI) cameras appear to also be supported by IDS Peak (see [here](https://www.1stvision.com/cameras/IDS/IDS-manuals/en/ueye-intro.html))

**Describe the solution you'd like to implement**
A camera class using IDS Peak API

**Describe alternatives you've considered**
buying old cameras

**Comment by csoeller** [comment]
We also find purchasing any of the older IDS camera models virtually impossible. I would support the idea moving to their newer cams and building an IDS Peak based interface. Have you yet looked at how different the Peak based interface would have to be?

**Comment by David-Baddeley** [comment]
Sounds good to me ...

**Comment by barentine** [comment]
Just an update that we have an IDS Peak only camera inbound - will give this a try at some point

**Comment by barentine** [comment]
addressed with merge of #1454
