### ISSUE TITLE
How should one add jinja filters to recipes.output.ReportOutput environment?

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#134]
I've written a plugin including a report template. I currently have my filter defined/added to the environment in `myplugin/reports/__init__.py`, which works fine if I import and `reports.env.get_template()`. My filter is very plugin-specific and does not belong (as I assume most will not) in PYME.recipes.output - how should I add it to the standard environment?

**Comment by zacsimile** [comment]
Seeing as this is merged, can we close this issue?
