### ISSUE TITLE
[ENHANCEMENT] Would it be worth getting sphinx to put more docstrings on the website than we currently have?

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#1377]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when someone asks me what a function does and I send them a screenshot of a docstring rather than a link to our documentation. This is mostly an issue for functions people add from the GUI, since the recipe docstrings display if adding a module.

**Describe the solution you'd like**
If someone asks me what's up with Area calculation for PYMEVis > Analysis > Measure objects, I'd like for them to 
- have a tool tip that tells them something e.g. at least what to search on our site maybe
- be able to search our doc and find something. For example: [objectMeasure](https://www.python-microscopy.org/doc/api/PYME.Analysis.points.objectMeasure.html) would ideally contain the docstrings for the functions in objectMeasure, e.g. `measure`, not just a blank page

**Describe alternatives you've considered**
manually writing doc

**Comment by David-Baddeley** [comment]
This is likely a bug in either docstring formatting or sphinx invocation - We should show all the docstrings. Solution is to look for errors in the output - the most likely cause is would be for `objectMeasure` to import a module which is neither available in the build environment nor mocked up `docs/conf.py`. In general we want to generate docs in a stripped down environment and mock modules which are not present rather than generating docs in a full environment as doing the later tends to result in the duplication of lots of 3rd party docs.

**Comment by David-Baddeley** [comment]
In terms of GUI menu functions, the long term vision here is to make *everything* recipe modules under the hood, and to piggy back off the documentation there.

**Comment by David-Baddeley** [comment]
For object measurement in particular, we also really need to get onto #524 , and it wouldn't hurt to have some manual documentation / a howto as it's typically a multi-step process (choose channel, segment, label, measure, optionally aggregate).

**Comment by David-Baddeley** [comment]
On a local build with #1408, we get `objectMeasures` docstrings correctly formatted (although the docstrings themselves could use a little work):

<img width="1129" alt="image" src="https://github.com/python-microscopy/python-microscopy/assets/19475296/9e834278-8460-46d3-8781-2f37b30ab01c">

**Comment by David-Baddeley** [comment]
and now fixed on the website (turns out you need to build the c coded extensions for objectMeasure to get generated)

**Comment by David-Baddeley** [comment]
@barentine
Having fixed the documentation build issue, can we close this? We haven't really addressed the tooltip issue (or general documentation quality issues), but this seems overly specific for those.

**Comment by barentine** [comment]
Yes! Thanks @David-Baddeley . Really nice to have this working
