### ISSUE TITLE
[ENHANCEMENT] Ability to install plugins in the one-click install version of PYME.

### ISSUE THREAD

**Issue by lukasfue** [python-microscopy/python-microscopy#1381]
**Is your feature request related to a problem? Please describe.**
Some users like the simplicity of the one-click install, but it seems that it isn't possible to install plugins without a development install of PYME (or at least it wasn't obvious to me how to do so).

**Describe the solution you'd like**
Making it possible to install plugins to the one-click install PYME version and instructions on how to do so (or just the latter if it is already possible).

**Comment by David-Baddeley** [comment]
Short answer - it's no different to a development install.

Longer answer - on windows the executable installer drops a link to the
anaconda prompt associated with the install, simply open that and `conda
install -c your_channel your-plugin`

Even longer answer - the above depends on the conda package for your plugin
having been built correctly (such that it drops the relevant config files
in the *dist* settings folder and they get copied into the package). As far
as I know, ch-shrinkwrap is the only plugin to do so (see build recipe in
the pyme-conda-recipes repo).

The plugin process and structure does need a bit more documentation in
general, along with a rework of the example repo

**Comment by barentine** [comment]
@lukasfue if you hit the windows key and type `anaconda prompt` the search should show you the anaconda prompt @David-Baddeley is talking about under `Apps` with some parenthesis around a name associated with your executable install. Something like: 
![image](https://github.com/python-microscopy/python-microscopy/assets/31105780/6ab6b031-daaf-4eb4-b904-5585647b02f0)



More broadly though, sounds like we could use:
- [ ] a Plugins page under the Installation docs. Ideally this should show people how to install both conda and source plugins, and give enough details on how to find the anaconda prompt gifted them by their executable install (if that's the route they took)
![image](https://github.com/python-microscopy/python-microscopy/assets/31105780/07488bdf-e385-4e17-8855-9d021b2f5b51)
- [ ] An update to the plugin template repository to actually handle dist settings properly (note @csoeller raised this some time back [here](https://github.com/python-microscopy/pyme-plugin/issues/8)). Note for others we discussed the need to update that repository last week - it's currently set up to help folks with a deprecated module discovery, and the new yaml config is simpler.
- [ ] a Plugin's page on the main website? Somewhere we can list plugins so folks can easily find them. `ch_shinkwrap` might be a great example, but you cannot currently discover it (or it's preprint) from the PYME website or docs

**Comment by lukasfue** [comment]
Thank you David and Andrew. The key was finding that Anaconda Prompt specific to PYME.

Best,
Lukas
