### ISSUE TITLE
Cannot create dark and variance maps from dh5view

### ISSUE THREAD

**Issue by HelenSun09** [python-microscopy/python-microscopy#140]
There is no menu option to generate dark and variance maps from within dh5view. This would be preferable to running

`python .\gen_sCMOS_maps.py "C:\Users\Helen Sun\Desktop\20200113_Dark map_50fps_000_000.dcimg"`

**Comment by David-Baddeley** [comment]
Absolutely, it's been on the wishlist for a while.

**Comment by barentine** [comment]
@David-Baddeley or @HelenSun09  I think this can be closed now
