### ISSUE TITLE
[BUG] "test this frame" always tests on first frame of sequence regardless of current frame position

### ISSUE THREAD

**Issue by csoeller** [python-microscopy/python-microscopy#1423]
**Describe the bug**
Whenever one tries "Test this frame" with the LMAnalyser in dh5view, only the first frame is tested, the logic to find the current frame positions seems broken (presumably still from pre-5D data times):

![Screenshot 2023-09-15 at 11 50 52](https://github.com/python-microscopy/python-microscopy/assets/3750860/46c4c721-a0ff-4bfe-a54b-505b77a13ead)

and the shown event locations all are from frame 0:

![Screenshot 2023-09-15 at 11 51 12](https://github.com/python-microscopy/python-microscopy/assets/3750860/99471bac-0d86-4b11-aea2-d85a73d7b64b)

**To Reproduce**
1. Go to 'Test this frame' in `dh5view`
2. Be sure to be on a later frame number in the view
3. Press 'Test this frame'
4. See that always frame 0 is tested

**Expected behavior**
It should test on the current frame.

**Screenshots**
Attached above.

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 Checked on latest github `Master` on macos.

**Comment by David-Baddeley** [comment]
An embarrassing regression, thanks for spotting it!
