### ISSUE TITLE
Cameras: GetElectronsPerCount, GetNoiseProperties, or both?

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#143]
`HDFSpoolFrame` looks calls `scope.cam.GetElectronsPerCount` when setting quantization scale. This is only implemented on the ucam480 stuff, while `GetNoiseProperties` is a method of the base Camera class. 

I'll submit a PR to instead call getnoiseproperties in hdfspoolframe. Should we also change the calls in the ucam code?

**Comment by David-Baddeley** [comment]
as discussed in #144 things are now unified around the `noise_properties` attribute (which should have been in the base class from the start). Can probably close this now.
