### ISSUE TITLE
Possible solution to random crashes with PCO SDK

### ISSUE THREAD

**Issue by pierrethibault** [python-microscopy/python-microscopy#1476]
I contacted PCO support about random crashes in their python PCO package (https://pypi.org/project/pco/). With a bit of back and forth they identified a bug in their package that seems to solve the problem: the `ZzdwDummy` field in the `PCO_Description` structure should be longer than 4 bytes, probably because new fields have been added in the dll while the SDK documentation wasn't updated. 

In your package, this corresponds to this line:

https://github.com/python-microscopy/python-microscopy/blob/f3f9e4b01bb3c41eb19df8c566baa769ecaa9095/PYME/Acquire/Hardware/pco/pco_sdk.py#L96

Replacing `ctypes.wintypes.DWORD` with `40*ctypes.wintypes.DWORD` does the trick.

**Comment by David-Baddeley** [comment]
Many thanks! That's been a consistent issue for us for a while, and we've never managed to figure it out.

@Yujin-Bao , @zacsimile
