### ISSUE TITLE
[BUG] Unable to restore layers tab after unpinning on macOS

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#1499]
**Describe the bug**
If I unpin the layers tab and then close it, I cannot restore it. Instead, the ellipses just toggle on and off.

<img width="1012" alt="image" src="https://github.com/python-microscopy/python-microscopy/assets/1263313/e6c0e8c5-c450-4ae1-af76-f73536583fbf">

<img width="1012" alt="image" src="https://github.com/python-microscopy/python-microscopy/assets/1263313/8faf42a4-515e-4613-afeb-cfbb95639576">

<img width="1012" alt="image" src="https://github.com/python-microscopy/python-microscopy/assets/1263313/6ccbf46c-e06b-418c-a418-b3170d6a64a4">

<img width="1012" alt="image" src="https://github.com/python-microscopy/python-microscopy/assets/1263313/4755ff8c-9b3e-4262-b80d-3d87c2c68a96">

<img width="1012" alt="image" src="https://github.com/python-microscopy/python-microscopy/assets/1263313/6085c0cb-83b3-467b-a618-374a0d31f21c">

<details>
<summary>Environment</summary>
<pre>
# packages in environment at /Users/zachcm/miniforge3/envs/pyme:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
annotated-types           0.6.0              pyhd8ed1ab_0    conda-forge
aom                       3.5.0                h7ea286d_0    conda-forge
asgiref                   3.7.2              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
autocommand               2.2.2              pyhd8ed1ab_0    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.zoneinfo        0.2.1            py38hb192615_8    conda-forge
blosc                     1.21.5               hc338f07_0    conda-forge
brotli                    1.0.9                hbdafb3b_4    conda-forge
brotli-python             1.0.9            py38h2b1e499_9    conda-forge
brunsli                   0.1                  h9f76cd9_0    conda-forge
bzip2                     1.0.8                h93a5062_5    conda-forge
c-ares                    1.24.0               h93a5062_0    conda-forge
c-blosc2                  2.11.3               h8eb3132_0    conda-forge
ca-certificates           2023.11.17           hf0a4a13_0    conda-forge
cairo                     1.18.0               hd1e100b_0    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cffi                      1.16.0           py38h73f40f7_0    conda-forge
cfitsio                   4.2.0                h2f961c4_0    conda-forge
ch-shrinkwrap             0.0                       dev_0    <develop>
charls                    2.4.2                h13dd4ca_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
cheroot                   10.0.0             pyhd8ed1ab_0    conda-forge
cherrypy                  18.8.0           py38h10201cd_3    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.1            py38h9afee92_1    conda-forge
cryptography              41.0.7           py38h8aaf554_1    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cython                    3.0.7            py38hb9fa5a8_0    conda-forge
dav1d                     1.2.1                hb547adb_0    conda-forge
django                    4.2.8              pyhd8ed1ab_0    conda-forge
docutils                  0.20.1           py38h10201cd_3    conda-forge
expat                     2.5.0                hb7217d7_1    conda-forge
fftw                      3.3.10          nompi_h3046061_108    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.47.0           py38h336bac9_0    conda-forge
freetype                  2.12.1               hadb7bae_2    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
giflib                    5.2.1                h1a8c8d9_3    conda-forge
glib                      2.78.1               h9e231a4_0    conda-forge
glib-tools                2.78.1               h9e231a4_0    conda-forge
gst-plugins-base          1.22.7               h040e9b9_0    conda-forge
gstreamer                 1.22.7               hd492984_0    conda-forge
hdf5                      1.14.2          nompi_h3aba7b3_100    conda-forge
icu                       73.2                 hc8870d7_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
ifaddr                    0.2.0              pyhd8ed1ab_0    conda-forge
imagecodecs               2023.1.23        py38hb315e43_2    conda-forge
imageio                   2.33.1             pyh8c1a49c_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        7.0.1              pyha770c72_0    conda-forge
importlib-resources       6.1.1              pyhd8ed1ab_0    conda-forge
importlib_metadata        7.0.1                hd8ed1ab_0    conda-forge
importlib_resources       6.1.1              pyhd8ed1ab_0    conda-forge
inflect                   7.0.0              pyhd8ed1ab_0    conda-forge
jaraco.classes            3.3.0              pyhd8ed1ab_0    conda-forge
jaraco.collections        5.0.0              pyhd8ed1ab_0    conda-forge
jaraco.context            4.3.0              pyhd8ed1ab_0    conda-forge
jaraco.functools          4.0.0              pyhd8ed1ab_0    conda-forge
jaraco.text               3.12.0           py38h10201cd_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h93a5062_3    conda-forge
kiwisolver                1.4.5            py38h9afee92_1    conda-forge
krb5                      1.21.2               h92f50d5_0    conda-forge
lazy_loader               0.3                pyhd8ed1ab_0    conda-forge
lcms2                     2.15                 hd835a16_1    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libaec                    1.1.2                h13dd4ca_1    conda-forge
libavif                   0.11.1               h9f83d30_2    conda-forge
libblas                   3.9.0           20_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_9    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_9    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_9    conda-forge
libcblas                  3.9.0           20_osxarm64_openblas    conda-forge
libclang                  15.0.7          default_hd209bcb_4    conda-forge
libclang13                15.0.7          default_ha49e599_4    conda-forge
libcurl                   8.4.0                h2d989ff_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libdeflate                1.18                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h93a5062_2    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           13_2_0_hd922786_1    conda-forge
libgfortran5              13.2.0               hf226fd6_1    conda-forge
libglib                   2.78.1               hd9b11f9_0    conda-forge
libiconv                  1.17                 h0d3ecfb_2    conda-forge
libjpeg-turbo             2.1.5.1              hb547adb_1    conda-forge
liblapack                 3.9.0           20_osxarm64_openblas    conda-forge
libllvm15                 15.0.7               h2621b3d_4    conda-forge
libnghttp2                1.58.0               ha4dd798_0    conda-forge
libogg                    1.3.4                h27ca646_1    conda-forge
libopenblas               0.3.25          openmp_h6c19121_0    conda-forge
libopus                   1.3.1                h27ca646_1    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libpq                     15.4                 hcea71ed_2    conda-forge
libsqlite                 3.44.2               h091b4b1_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libtiff                   4.5.1                h23a1a89_1    conda-forge
libvorbis                 1.3.7                h9f76cd9_0    conda-forge
libwebp-base              1.3.2                hb547adb_0    conda-forge
libxcb                    1.15                 hf346824_0    conda-forge
libxml2                   2.12.3               h0d0cfa8_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
libzopfli                 1.0.3                h9f76cd9_0    conda-forge
llvm-openmp               17.0.6               hcd81f8e_0    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
markupsafe                2.1.3            py38hb192615_1    conda-forge
matplotlib                3.7.3            py38h150bfb4_0    conda-forge
matplotlib-base           3.7.3            py38hef9d0d7_0    conda-forge
more-itertools            10.1.0             pyhd8ed1ab_0    conda-forge
mpld3                     0.5.10             pyhd8ed1ab_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.33               hf9e6398_6    conda-forge
mysql-libs                8.0.33               he3dca8b_6    conda-forge
ncurses                   6.4                  h463b476_2    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
nspr                      4.35                 hb7217d7_0    conda-forge
nss                       3.96                 h5ce2875_0    conda-forge
numexpr                   2.8.4            py38hefb543e_1    conda-forge
numpy                     1.24.4           py38ha84db1f_0    conda-forge
openjpeg                  2.5.0                hbc2ba62_2    conda-forge
openssl                   3.1.4                h0d3ecfb_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3            py38hefb543e_1    conda-forge
pathlib2                  2.3.7.post1      py38h10201cd_3    conda-forge
pcre2                     10.40                hb34f9b4_0    conda-forge
pillow                    10.0.0           py38h3f590de_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pixman                    0.42.2               h13dd4ca_0    conda-forge
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.8.0              pyhd8ed1ab_0    conda-forge
portend                   3.2.0              pyhd8ed1ab_0    conda-forge
psutil                    5.9.7            py38h336bac9_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
pycairo                   1.25.1           py38hc4154ad_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  2.5.3              pyhd8ed1ab_0    conda-forge
pydantic-core             2.14.6           py38h51b07bf_1    conda-forge
pyface                    8.0.0              pyhd8ed1ab_0    conda-forge
pyfftw                    0.12.0           py38h22c8ccb_3    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pymecompress              0.3.6                    pypi_0    pypi
pyopengl                  3.1.6              pyhd8ed1ab_1    conda-forge
pyopenssl                 23.3.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pypubsub                  4.0.3                      py_0    conda-forge
pyqt                      5.15.9           py38h951d1d4_5    conda-forge
pyqt5-sip                 12.12.2          py38he333c0f_5    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytables                  3.8.0            py38hcf313c7_4    conda-forge
python                    3.8.18          h2469fbe_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-microscopy         23.6.15.post0.dev0           dev_0    <develop>
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python.app                1.4              py38h298bfb8_3    conda-forge
python_abi                3.8                      4_cp38    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1            py38h5912bca_1    conda-forge
pywin32                   306              py38h150bfb4_2    conda-forge
pyyaml                    6.0.1            py38hb192615_1    conda-forge
qt-main                   5.15.8              h219f738_16    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
repoze.lru                0.7                        py_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
routes                    2.5.1              pyhd8ed1ab_0    conda-forge
scikit-image              0.21.0           py38he333c0f_0    conda-forge
scikit-learn              1.3.2            py38he1bc1c9_2    conda-forge
scipy                     1.10.1           py38h038e806_3    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
simplejson                3.19.2           py38h336bac9_0    conda-forge
sip                       6.8.1            py38hb9fa5a8_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h17c5cce_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sphinx                    7.1.2              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
sqlparse                  0.4.4              pyhd8ed1ab_0    conda-forge
tempora                   5.5.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tifffile                  2023.7.10          pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h5083fa2_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toposort                  1.10               pyhd8ed1ab_0    conda-forge
tornado                   6.3.3            py38hb192615_1    conda-forge
traits                    6.4.3            py38h336bac9_0    conda-forge
traitsui                  8.0.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.9.0                hd8ed1ab_0    conda-forge
typing_extensions         4.9.0              pyha770c72_0    conda-forge
tzdata                    2023d                h0c530f3_0    conda-forge
ujson                     5.9.0            py38hde5fecb_0    conda-forge
unicodedata2              15.1.0           py38hb192615_0    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
wxpython                  4.2.1            py38ha92163b_0    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
zc.lockfile               3.0.post1          pyhd8ed1ab_0    conda-forge
zeroconf                  0.131.0            pyhd8ed1ab_0    conda-forge
zfp                       1.0.1                ha8f4885_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zlib-ng                   2.0.7                h1a8c8d9_0    conda-forge
zstd                      1.5.5                h4f39d0f_0    conda-forge
</pre>
</details>

**Comment by pjouchet** [comment]
I have hit the same bug
<details> <summary> environment </summary>

```
# packages in environment at C:\ProgramData\Anaconda3\envs\pymedev:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.13                   pypi_0    pypi
autocommand               2.2.2                    pypi_0    pypi
babel                     2.14.0                   pypi_0    pypi
blas                      1.0                         mkl
ca-certificates           2024.3.11            haa95532_0
certifi                   2022.12.7        py37haa95532_0
charset-normalizer        3.3.2                    pypi_0    pypi
cheroot                   10.0.1                   pypi_0    pypi
cherrypy                  18.9.0                   pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    3.0.10                   pypi_0    pypi
docutils                  0.19                     pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
idna                      3.7                      pypi_0    pypi
ifaddr                    0.2.0                    pypi_0    pypi
imageio                   2.31.2                   pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        6.7.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
inflect                   6.0.5                    pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
jaraco-collections        4.2.0                    pypi_0    pypi
jaraco-context            4.3.0                    pypi_0    pypi
jaraco-functools          3.7.0                    pypi_0    pypi
jaraco-text               3.11.1                   pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py37h2bbff1b_0
mkl_fft                   1.3.1            py37h277e83a_0
mkl_random                1.2.2            py37hf11a4ad_0
more-itertools            9.1.0                    pypi_0    pypi
mpld3                     0.5.10                   pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
numexpr                   2.8.6                    pypi_0    pypi
numpy                     1.21.5           py37h7a0a035_3
numpy-base                1.21.5           py37hca35cd5_3
openssl                   1.1.1w               h2bbff1b_0
packaging                 24.0                     pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       22.3.1           py37haa95532_0
portend                   3.1.0                    pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
pydantic                  1.10.15                  pypi_0    pypi
pyface                    8.0.0                    pypi_0    pypi
pyfftw                    0.13.0                   pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pymecompress              0.3.6                    pypi_0    pypi
pyopengl                  3.1.7                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.7.16               h6244533_0
python-dateutil           2.9.0.post0              pypi_0    pypi
python-microscopy         23.6.15.post0.dev0           dev_0    <develop>
pytz                      2024.1                   pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
setuptools                65.6.3           py37haa95532_0
six                       1.16.0             pyhd3eb1b0_1
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    5.3.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
tables                    3.7.0                    pypi_0    pypi
tempora                   5.3.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
toposort                  1.10                     pypi_0    pypi
traits                    6.4.3                    pypi_0    pypi
traitsui                  8.0.0                    pypi_0    pypi
typing-extensions         4.7.1                    pypi_0    pypi
ujson                     5.7.0                    pypi_0    pypi
urllib3                   2.0.7                    pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.38.4           py37haa95532_0
wincertstore              0.2              py37haa95532_2
wxpython                  4.0.4            py37ha925a31_0
zc-lockfile               3.0.post1                pypi_0    pypi
zeroconf                  0.26.3                   pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
```

</details>

**Comment by David-Baddeley** [comment]
Definitely confirmed - I'm pretty sure this is a long-standing issue with nested fold panels (see note starting on line 372 in manualFoldPanel.py), although might have been exacerbated with recent fold panel changes. 

Have a few tweaks in progress which should hopefully address this, but still running into a bit of a brick wall. It's proving remarkably difficult.

The root problem is that the fold panel reports an incorrect (small) minimum size.

An interim workaround is simply not to unpin the layers panel.

**Comment by David-Baddeley** [comment]
Think I've finally nailed it! See linked commit on the dark ui  PR
