### ISSUE TITLE
Make free space estimate work for cluster spooling

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#150]
As per title (see also #147 ). This is a blocker for Py3.

**Comment by barentine** [comment]
What is blocking this on py3?

**Comment by David-Baddeley** [comment]
This is, in my view, a blocking bug for moving many of our users to cluster
of one streaming and python3. It's really hard to tell people to upgrade if
it results in a loss of functionality.

**Comment by barentine** [comment]
fixed in #253. Mind closing it when you get the chance @David-Baddeley?

**Comment by barentine** [comment]
can close this

**Comment by barentine** [comment]
tidying issues before I open another one. Can close this @David-Baddeley
