### ISSUE TITLE
[BUG] pymevis: possible bug with new OpenGL core profile viewpoint mapping/manipulation

### ISSUE THREAD

**Issue by csoeller** [python-microscopy/python-microscopy#1533]
**Describe the bug**
I am suspecting that there _could_ be a small bug with the axes in viewpoint manipulation with the new openGL core stuff.

**To Reproduce**
1. Produce old style behaviour with `--opengl-compatibility-profile` flag, click marked orientation button and get the expected view of the data, see schreenshot 1, i.e. side on view with the data in the horizontal.
2. Produce new behaviour with `--opengl-core-profile`, click same marked orientation button, now get different view of data, see screenshot 2, i.e. side on view but now data in the vertical. In line with that, horizontal mouse pointer movement (button pressed) now rotates the data downward (see arrows), instead of anticipated rotation around a vertical viewport axis. I suspect these two behaviours are the results of the same "axis confusion", but just a wild guess.

I noticed this when trying to rotate my views and my view-movement manipulation seemed to not work as before.

**Expected behavior**
Original rotation behaviour with new style core profile.

**Screenshots**

Screenshot 1 (compat profile):
<img width="1012" alt="Screenshot 2024-08-07 at 09 27 24" src="https://github.com/user-attachments/assets/b7308f95-14b8-455d-8eb2-6517f5f767a4">

Screenshot 2 (new core profile):
<img width="1012" alt="Screenshot 2024-08-07 at 09 28 35" src="https://github.com/user-attachments/assets/e114ae0c-e243-4d46-a24e-b0af1d99fc9f">

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: tested on mac so far

**Comment by David-Baddeley** [comment]
Thanks! was a simple transpose in the rotation matrix convention.

**Comment by csoeller** [comment]
Excellent, @David-Baddeley, thanks for the quick fix!
