### ISSUE TITLE
Data pipeline not displaying in VisGUI

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#157]
The data pipeline seems to have disappeared from VisGUI in the latest versions.

**Comment by David-Baddeley** [comment]
What platform? Wx version? Any error messages in console?

I get no issues with the current head on OSX with both py2, wx3 and py3 wx4.

**Comment by zacsimile** [comment]
It seems to be back. It was gone for a few versions on both my Mac/Windows. Not sure what happened.

**Comment by David-Baddeley** [comment]
That's super weird. Would be good to know where it went.
