### ISSUE TITLE
Cannot scroll through docstrings within Bakeshop on Windows 10

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#162]
When the docstring shows up in the add module window in Bakeshop, if it's longer than the window, a scroll bar pops up, but the scroll bar doesn't work.

**Comment by David-Baddeley** [comment]
What wx version, python version? (I suspect this is a wx4 bug, but hard to be sure)

**Comment by zacsimile** [comment]
wxpython 4.0.4
python 3.6.7

**Comment by David-Baddeley** [comment]
Platform? Any console output that might be useful?

**Comment by zacsimile** [comment]
Platform is Windows 10. I didn't see any useful console output, but maybe I can force it.

**Comment by zacsimile** [comment]
No console output at all.

**Comment by David-Baddeley** [comment]
Working fine with wx4, py3 on OSX.
