### ISSUE TITLE
text trimming a bit odd in LMAnalysis panel

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#180]
ubuntu 16.04 LTS, wxpython 4.0.4, python 3.6.9, traits 6.1.0, traitsui 6.2.0

Text can be trimmed in an awkward way such maps which should be found automatically from metadata may appear to be blank
![image](https://user-images.githubusercontent.com/31105780/76363710-fd0ba900-62f9-11ea-8511-5e7d4cdd679c.png)
Though one can check by manually expanding the panel.
![image](https://user-images.githubusercontent.com/31105780/76363679-f0875080-62f9-11ea-83a3-ddf75d9176f6.png)
There's also an odd in-between spot where you get just a piece of the underscore for some reason
![image](https://user-images.githubusercontent.com/31105780/76363806-2d534780-62fa-11ea-9e8d-8319baab60c9.png)

If you use the 'Set' button, then it tries to display the map name regardless of panel size:
![image](https://user-images.githubusercontent.com/31105780/76363945-7dcaa500-62fa-11ea-9e4c-9deece874386.png)
![image](https://user-images.githubusercontent.com/31105780/76363977-8b802a80-62fa-11ea-996d-48d696738ff8.png)

**Comment by David-Baddeley** [comment]
Not sure there is an easy fix to this - it's somewhat offset for practical use by the colour-coding so that you at least know if there is a map set (and can expand the panel to see the filename).

**Comment by barentine** [comment]
Figured it wouldn't be worth the time investment to sort out but thought I'd raise it just in case. Thanks David.
