### ISSUE TITLE
Make MATLAB loading CSV-style

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#194]
Convert the MATLAB loader so it has a single entry point and pops up with a GUI for mapping MATLAB workspace fields to PYME dataSource fields, just like we do when loading CSV files.

**Comment by zacsimile** [comment]
First off, correcting myself, the MATLAB loader does have a single entry point.

Follow up on personal communications with @David-Baddeley:

We decided to have MATLAB automatically load without a GUI popup if it can find `x` and `y` variables. If there are only a couple of variables, and either `x` or `y` cannot be found, it will default to old-style MATLAB loading. Otherwise, if there are a lot of variables, and either `x` or `y` cannot be found, a CSV-style GUI variable-mapping window will pop up.

**Comment by zacsimile** [comment]
Addressed in #229

**Comment by David-Baddeley** [comment]
now merged
