### ISSUE TITLE
DBSCAN dialog not displaying most fields on Python 3, OSX

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#199]
<img width="291" alt="Screen Shot 2020-03-29 at 7 05 41 PM" src="https://user-images.githubusercontent.com/1263313/77863487-dbaf2600-71f0-11ea-9c08-751a260bfd53.png">

`wxpython 4.04`
`traits 5.1.1`
`traitsui 6.1.1`

```
AttributeError: 'ImageControl' object has no attribute 'GetClientSizeTuple'
Traceback (most recent call last):
  File "/anaconda3/envs/pyme/lib/python3.6/site-packages/traitsui/wx/image_control.py", line 194, in _on_paint
    wdx, wdy = self.GetClientSizeTuple()
```

**Comment by zacsimile** [comment]
This is what I get if I try to click in to the hidden fields. The same `AttributeError` just spools on the screen as I do this.

<img width="289" alt="Screen Shot 2020-03-29 at 7 13 24 PM" src="https://user-images.githubusercontent.com/1263313/77863566-62640300-71f1-11ea-9701-d99dcc0af1c7.png">

**Comment by David-Baddeley** [comment]
This is a traitsui bug.

potential workarounds:

- downgrade wx to the lowest version you can on Py3
- write a custom view to force the use of a different editor for the trait (see comments on #200 )
