### ISSUE TITLE
Ripley's analysis is not working

### ISSUE THREAD

**Issue by lukasfue** [python-microscopy/python-microscopy#219]
I tried testing the new Ripley's analysis using the default parameter values and got this traceback:

Traceback (most recent call last):
  File "c:\users\laf62\python-microscopy\PYME\LMVis\Extras\clusterAnalysis.py", line 411, in OnRipleys
    result = recipe.apply(inputPositions=pipeline.selectedDataSource, inputMask=mask)
AttributeError: 'ModuleCollection' object has no attribute 'apply'

**Comment by barentine** [comment]
Looks like that `apply()` should be an `execute()`. Thanks @lukasfue.

**Comment by barentine** [comment]
oops, `recipe` should be `r`. Anyway, we'll take care of it

**Comment by zacsimile** [comment]
I'm taking care of it now. Almost there, I think. There were a few other slight bugs after fixing `apply`.

**Comment by David-Baddeley** [comment]
Apply is correct, not execute

**Comment by zacsimile** [comment]
`apply` is correct for the recipe, not for the `ModuleCollection`. I switched to using `apply` on the recipe (it was previously on the `ModuleCollection`). Fixes are coming shortly. I'm just testing them on real data right now to make sure they work.

**Comment by zacsimile** [comment]
I pushed fixes in #220 that make this run now (tested on 2D and 3D data/masks). I'm not 100% sure the graphs coming out make sense. Will need to test on some more data structures/more masks to confirm. We are passing tests for `PYME.analysis.points.ripleys.ripleys_k_from_mask_points()`, so at least that part should be correct.

**Comment by zacsimile** [comment]
This was fixed with the merge of #220. I think we can close.
