### ISSUE TITLE
Animation improvements

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#223]
#222 restores the animation panel to its former glory, but I think we can do more. Ideally we'd be able to 

- [x] set the number of frames between each view
- [x] set the output pixel size (or at least scale factor)
- [x] choose the output file type (JPG, PNG)
- [x] fix the coloring, particularly on the LUT bar in exported animations

It looks like Michael Graff started implementing some of these ideas in `PYME.LMVis.Extras.animation.EditPanel` and `EditDialog`. Did we make a decision not to use the `EditPanel`? Or was it never finished? Are there additional features we'd like to add to our animation module?

(Almost) everything I've proposed above is already implemented on the backend. What we should discuss here is how we want it implemented in the GUI.

**Comment by David-Baddeley** [comment]
- I'd favour keeping 'Save' and 'Make' as separate buttons (ideally renaming 'Make' to 'Export') so that 'Save' refers to the key frames and other bits (something you can reload on other data) and Export gives you an option between JPG, PNG, and AVI (if you have openCV installed).
- setting the number of frames between views and setting the frame rate are a bit redundant when exporting individual images.
- what is wrong with the colouring?

The `EditDialog` gets displayed when you double click on one of the views. It would probably make more sense to have the duration as an additional column.

**Comment by zacsimile** [comment]
- Good point, we'll drop frame rate. 
- I agree duration should be an additional column rather than a popup.
- The coloring is very...psychedelic. If you export an animation, you'll see what I mean.

**Comment by zacsimile** [comment]
Can we add single TIFFs as an export option (not stacks)?

**Comment by zacsimile** [comment]
There were requests to add `time` and `alpha` changes to the animation. I think we'd just need to put these in `PYME.LMVis.views.View`. Doesn't seem terrible.

**Comment by David-Baddeley** [comment]
Was tidying and found the animation UI mockup I originally drew for Michael (with a duration column :p) 

![IMG_20170328_092203](https://user-images.githubusercontent.com/19475296/82623000-45691080-9c33-11ea-8556-769daa50afeb.jpg)

**Comment by zacsimile** [comment]
Cool! We can build this, we're already fairly close. I wonder if a duration column makes sense. The duration is associated with the transition from one view to the next, so I think it should show up in between views (maybe as an arrow with a time next to it), rather than as a column associated with a view, since this looks ambiguous. However, I think this would require making a non-standard window. I think, in this case, it may be necessary.

**Comment by David-Baddeley** [comment]
Although the duration is technically associated with the transition, I don't think it's awful to have it in the GUI on the same row as the view you are transitioning from - it's certainly not worth writing a custom UI component.

**Comment by zacsimile** [comment]
Most of these enhancements are made in #282.
