### ISSUE TITLE
Generate isosurface from Delaunay tessellation is broken 

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#241]
I'm almost positive this one's entirely my fault. I need to revisit it at some point. 

We should also probably think about the pipeline from a user's perspective. If you select `View > Create Delaunay Tesselation` (sp. tessellation), and then `View > Generate Isosurface from Delaunay Tesselation`, it won't work. It expects the field `dn` (density) from `Estimate density` or `Estimate density (circumcenters)`, which also create, but do not display, a tessellation. It's just a bit confusing.

Also these should probably not be in the `View` menu. I suggest we move most of it to `Analysis > Density` and the isosurface generation from Delaunay tessellation to `Mesh`.

**Comment by David-Baddeley** [comment]
Agree that it's a bit of a mess - At the moment I consider this pretty experimental, so there might be an argument for letting the use cases firm up somewhat before trying to do get the UI nailed. Maybe we need an "alpha" menu in VisGUI to put stuff that is in development.

**Comment by zacsimile** [comment]
Not a bad idea. Maybe `Extras>Alpha`?

Use cases would be helpful. However, I should be able to fix the marching tetrahedra without use-cases, I think.
