### ISSUE TITLE
Canceling the `Open raw/prebleach data` dialog throws a Traceback in the new context manager

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#247]
<img width="1012" alt="Screen Shot 2020-05-14 at 1 08 20 PM" src="https://user-images.githubusercontent.com/1263313/81964002-00fec480-95e4-11ea-841b-2339354492a0.png">

Btw, I really like the new context manager.

**Comment by zacsimile** [comment]
This isn't a context manager issue. Clicking `cancel` shouldn't throw a traceback.

**Comment by David-Baddeley** [comment]
Fixed in 7d08bbc
