### ISSUE TITLE
z stepping (and maybe some other stuff) currently disabled

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#291]
I suspect the spool controller settings.update refactor missed a bit
![image](https://user-images.githubusercontent.com/31105780/85793895-b94f7a80-b703-11ea-836a-25e00ad046cc.png)

`stack` is a startspool input parameter and defaults to `False`:
![image](https://user-images.githubusercontent.com/31105780/85794084-0895ab00-b704-11ea-90ae-b0626dd430da.png)

**Comment by barentine** [comment]
as mentioned in #292 there is also a bug for the compression setting.

Not mentioned there is that spool controller's z_dwell attribute will now override whatever you have in the protocol. I'm actually a huge fan of being able to override the protocol z_dwell, but we should probably make it optional and controllable through the gui

**Comment by David-Baddeley** [comment]
I'm not too worried about over-riding the protocol z_dwell - solution is probably just to remove/deprecate the z_dwell argument to the protocol.

**Comment by barentine** [comment]
Would it be OK to ~complete the settings-dict refactor on `SpoolController` and replace all the kwargs in `start_spooling` with a single `settings` parameter (dict) that gets passed to `update_settings` first thing in `start_spooling`? To ensure it's fast we might also want to change `update_settings` doesn't pop / call set methods unless it actually needs to

**Comment by barentine** [comment]
Fixed with merges of #292, #327 , and #285
