### ISSUE TITLE
[BUG] scalebar unit in dh5view looks like lm

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#367]
**Describe the bug**
![image](https://user-images.githubusercontent.com/31105780/88730183-871aa980-d103-11ea-9550-964f28ce0b83.png)
liter-meters

**To Reproduce**
open a series in dh5view on windows, py3

**Expected behavior**
um

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: [e.g. Win10] Win10
 - Python version: 3.6
 - numpy version: 1.16
 - wxpython version [if a UI bug]: 4.1.0

**Comment by David-Baddeley** [comment]
works fine on OSX, wx3, py2.7.

expected behaviour is to show a greek mu.

Likely a unicode literal problem (or windows font problem - do the std windows fonts support all unicode chars?).

See `PYME.DSViewer.LMAnalysis` line 354

**Comment by David-Baddeley** [comment]
If a windows font problem, could try substituting `'\u00B5'`

see https://www.fileformat.info/info/unicode/char/00b5/index.htm

**Comment by David-Baddeley** [comment]
`'\u00B5'` confirmed to work on OSX (so safe substitution if it works on windows)

**Comment by barentine** [comment]
Yep, that works.
![image](https://user-images.githubusercontent.com/31105780/88739622-f3e47280-d108-11ea-8a82-0242c0093c59.png)

Pretty sure this has been around for ages and is windows rather than py3/wx4, but I hardly use dh5view on windows, and I think people've just dealt with it.

Thanks David.

**Comment by barentine** [comment]
fixed in ce54ff2
