### ISSUE TITLE
[BUG] remFitBuf: CameraInfoManager slices contain non-integer indices

### ISSUE THREAD

**Issue by csoeller** [python-microscopy/python-microscopy#423]
**Describe the bug**

I hit what looked like a bug when trying to use my maptools plugin, part of PYME-extra:

```
Error whilst running Experimental>Map Tools>Show dark map
==============================================
python-microscopy=20.08.10
python=2.7.17, platform=darwin
numpy=1.16.6, wx=3.0.2.0 osx-cocoa (classic)

Traceback
=========
Traceback (most recent call last):
  File "/Users/csoe002/Documents/src/PYME-src/python-microscopy/PYME/ui/progress.py", line 107, in func
    return fcn(*args, **kwargs)
  File "/Users/csoe002/Documents/src/PYME-src/PYME-extra/PYMEcs/experimental/mapTools.py", line 399, in OnShowDark
    self.showMap(type='dark')
  File "/Users/csoe002/Documents/src/PYME-src/PYME-extra/PYMEcs/experimental/mapTools.py", line 377, in showMap
    darkf = self.ci.getDarkMap(mdh2)
  File "/Users/csoe002/Documents/src/PYME-src/python-microscopy/PYME/localization/remFitBuf.py", line 212, in getDarkMap
    mp = self._getMap(md, darkMapName)
  File "/Users/csoe002/Documents/src/PYME-src/python-microscopy/PYME/localization/remFitBuf.py", line 187, in _getMap
    map = np.concatenate([full_map[sl].astype('f') for sl in slices], axis=0)
TypeError: slice indices must be integers or None or have an __index__ method
```

**To Reproduce**
1. In dh5view
2. run the maptools plugin
3. Select show dark map

**Expected behavior**
Should retrieve dark map ok.

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
- python-microscopy=20.08.10
- python=2.7.17, platform=darwin
- numpy=1.16.6, wx=3.0.2.0 osx-cocoa (classic)

**Additional context - possible solution**
This looked like a situation where numpy has become more picky (used to be a warning I guess). The following patch appears to fix it. Please check if suitable.

```
diff --git a/PYME/localization/remFitBuf.py b/PYME/localization/remFitBuf.py
index 1ed8fbfa..2e9617b2 100644
--- a/PYME/localization/remFitBuf.py
+++ b/PYME/localization/remFitBuf.py
@@ -151,14 +151,14 @@ class CameraInfoManager(object):
             #special case handling for multiview ROIs
             origins = [md['Multiview.ROI%dOrigin' % ind] for ind in md['Multiview.ActiveViews']]
             size_x, size_y = md['Multiview.ROISize']
-            return [(slice(ox, ox + size_x), slice(oy, oy + size_y)) for ox, oy in origins]
+            return [(slice(int(ox), int(ox + size_x)), slice(int(oy), int(oy + size_y))) for ox, oy in origins]
         
         x0, y0 = get_camera_roi_origin(md)
 
         x1 = x0 + md['Camera.ROIWidth']
         y1 = y0 + md['Camera.ROIHeight']
 
-        return [(slice(x0, x1), slice(y0, y1))]
+        return [(slice(int(x0), int(x1)), slice(int(y0), int(y1)))]
 
     def _fetchMap(self, md, mapName):
         """retrive a map, with a given name. First try and get it from the Queue,

```

**Comment by barentine** [comment]
Would have to check, but just quickly reading this and having not hit the same issue myself, I'm wondering if the camera roi size / origin in your metadata isn't float rather than int - it might be nice to fix there there instead/as well.

**Comment by csoeller** [comment]
Yes, these are PYME generated files (using the dark/variance code) and indeed it has floats in the ROI specs. Wherever the type casts end up being, for robustness we should force at all the suitable places. Possibly the mean/vraiance code needs a cheup to not generate flota/double ROI indices as well.

<img width="912" alt="Screenshot 2020-08-20 at 20 27 03" src="https://user-images.githubusercontent.com/3750860/90816231-d7acad80-e323-11ea-92d4-d9aee1177e4f.png">

**Comment by David-Baddeley** [comment]
Think fixing at point of use is most robust (depending on how the metadata is saved, there might not be a distinction between int and float for numerical values, forcing everything to be coerced to float - .json in particular does not have explicit typing of numerical values)

**Comment by David-Baddeley** [comment]
PS definitely a case of numpy getting less tolerant ...

**Comment by David-Baddeley** [comment]
@csoeller - do you want to pop the patch in a PR, or should I just apply it? (effects author attribution in git but very little else)

**Comment by csoeller** [comment]
@David-Baddeley , happy for you to apply, saves me the hassle of preparing PR. I'll preapre one for the Zyla tweaks which now can deal with Zylan and Sona heads with the same code, a couple of points to discuss which I'll pop in a separate issue/message/PR.

**Comment by barentine** [comment]
I'm all for forcing at point of use, but was just curious as where we might be 'leaking' an int to float. I was under the impression json did a fine job leaving ints/floats alone - here's a metadata.json on the cluster for a series at random:
```
  "Camera.CycleTime": 0.004004932330827067,
  "Camera.EMGain": 1,
  "Camera.ElectronsPerCount": 0.416613,
  "Camera.IntegrationTime": 0.004004932330827067,
  "Camera.Model": "C11440-22C",
  "Camera.Name": "Hamamatsu ORCA Flash 4.0",
  "Camera.NoiseFactor": 1,
  "Camera.ROI": [
    720,
    872,
    1024,
    1176
  ],
  "Camera.ROIHeight": 304,
  "Camera.ROIOriginX": 720,
  "Camera.ROIOriginY": 872,
  "Camera.ROIWidth": 304,
  "Camera.ReadNoise": 0.997,
  "Camera.SensorHeight": 2048,
  "Camera.SensorWidth": 2048,
```

while for my camera map, generated same as @csoeller 's it sounds and saved as tif:
![image](https://user-images.githubusercontent.com/31105780/90824435-6b22b600-e305-11ea-8551-6dfabaa2a4c0.png)

Anyway, glad it's being taken care of, but I wouldn't be upset if we happened to catch it further upstream too. Maybe has something to do with the `OMEXMLMDHandler`

**Comment by David-Baddeley** [comment]
It might be the XML metadata handler in this case - my point was that as our metadata is, in general, not explicitly typed fixing it upstream is not really a robust solution (it's nice if it goes in as an int and comes out as an int, but things should work either way).

Should now be fixed with latest commit.
