### ISSUE TITLE
[ENHANCEMENT] Zyla backend and ControlPanel tweaks to support both Zyla and Sona

### ISSUE THREAD

**Issue by csoeller** [python-microscopy/python-microscopy#425]
**Is your feature request related to a problem? Please describe.**

This is a quick quick pre-discussion before submitting a PR for the small amount of backend tweaks that allow both Zyla and Sona heads to run with the Zyla backend.

**Describe the solution you'd like**

I have an implementation that required only a small set of tweaks to the original code. The main difference with the Sona from a user point of view are a number of selectable Tempearture Control modes, i.e. 0, -25 and -45 deg cooling. I have a screenshot below that this can be largely accomodated by having another enum control in the ZylaControlPanel.

Note the cyan box which allows access to selecting the cooling mode. With the Zyla, this just contains 0 deg as only choice.

I found that I also wanted to see the TemperatureStatus which I have implemented as a cludge to enum controls, see red box in screenshot. This is a readonly property and as such it is not the best way to show this as an enum control. It would be really good to infrequently update the status somewhere in the GUI as I found that the -45 setting never stablised and stayed at -38 or so. So this is most likely not the right solution but it would be good to briefly discuss how to tackle this one.

The remainder of the smallish tweaks will be more easily discussed once I prepared the PR. If I get some guidance how we can best tackle the TemperatureStatus I will take that into account when preparing the PR.

![sona-view-screen](https://user-images.githubusercontent.com/3750860/90905937-cd90ba80-e3c8-11ea-9ec1-d994b6bed780.jpg)

This is what the interface looks like with the Zyla. Just 0.0 by default re temp setting.

![zyla-view-screen-3](https://user-images.githubusercontent.com/3750860/90906622-da61de00-e3c9-11ea-83eb-ef1784693d46.jpg)

**Describe alternatives you've considered**
Nothing to say really.

**Additional context**
Screenshots are applied above.

**Are you prepared to work on it?**
Yep, already did.

**Comment by zacsimile** [comment]
@csoeller I'd love to see what you did. I ran into a lack of camera controls for the pco/orca and I'm currently writing (started this morning, nearly finished) a complete refactor of the camera controls that lets you do something like

```
ctrls = [BoolControl('SpuriousNoiseFilter'),
                etc.]
MyCamControl = CamControl(parent, cam, scope, ctrls)
```

for every camera. It seems like I may be duplicating efforts. Perhaps we should coordinate on this?

**Comment by csoeller** [comment]
@zacsimile, I just did minimal stuff and this is all heavily dependent on the SDK3 feature implementation (and its Python wrapping) which implements for every feature a bunch of access functions (`isImplemented`, `isWritable`, `getAvailableValues`, etc) that is already used in the current Zyla and ZylaControlPanel code. One possibility would be to mimic that approach and mimic these objects for other cameras as well so that they are method equivalent. I am sure @David-Baddeley will know what I mean and can judge if that is a good approach or not.

PS - your control implementation above is at a higher level than what I have done and the refactoring that you are doing can most likely be straight mapped onto my Sona mods which are really just tweaks of the current Zyla code. You can see it in my fork of python-microscopy on github and just inspect the `AndorZyla.py` and `ZylaControlPanel.py` files.

**Comment by csoeller** [comment]
I have now raised a PR, issue #429, to make it easier to discuss the points raised above.

**Comment by David-Baddeley** [comment]
My preference would be to not show the temperature controls where they are not needed (Zyla), and also not to show the stabilised as a dropdown, but suspect these are small tweaks which I can have a look at after the fact when I'm in front of a computer with a camera.

**Comment by David-Baddeley** [comment]
I think we should be able to close this with #429
