### ISSUE TITLE
[ENHANCEMENT] Use django.dispatch instead of old, broken, copy-pasted django.dispatch

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#430]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when we run into problems that have been solved by a robust development community. Our current `dispatch` is copy-pasted from an ancient version of django's dispatch module. We occasionally run into issues with it (#424), and django itself is an 'optional' dependency already. Additionally, while not a big issue to build from a git, it is still packaging overhead, which can lead to confusion/frustration (#126). As we move to py3, I think it would be worth considering moving to `django.dispatch`. Come January we could consider bumping django versions further if we like, as `django.dispatch` is pretty stable.

**Additional context**
Previous points have been made as to not adding django as a 'core dependency', for which I'll express counter positions:
> Django breaks backwards compatibility really fast

They may, but they continue to support the older versions long afterwards (largely motivated by security concerns, latest 1.x release was March of this year despite 2.x being released in 2017). Additionally the part we would use for the 'core' PYME, i.e. dispatch, is [very stable](https://github.com/django/django/blame/master/django/dispatch/dispatcher.py). 

> For security reasons, it's always a good idea to run the latest version of django (this means we can't / shouldn't pin to a fixed version of django)

Django releases security patches for all known affected versions see [here](https://docs.djangoproject.com/en/3.1/releases/#security-releases). Also, django.dispatch itself, e.g. the 'core' dependency does not add a security risk (and if it did, using unsupported ancience dispatch would be worse), so adding django as core dep and using django.dispatch instead of django is moot re:security.
> Django is a big package with loads of dependencies (makes satisfying these as well as all the standard PYME dependencies a headache, particularly on conda)

I regularly install django via conda with all my pyme stuff. Which of their dependencies are causing worry here? My feeling is that the dependencies outside of the 'scientific stack' make it pretty unlikely we conflict.

**Are you prepared to work on it?**
would happily test/pr/etc.

**Comment by David-Baddeley** [comment]
We've had this discussion multiple times and done it to death. Django is not coming in as a core dependency. We do need to sort out dispatch, but this in not the right way to do it.
