### ISSUE TITLE
[BUG] PYME.IO.rgb_image.image_to_cmy gives all zeros for greyscale

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#452]
**Describe the bug**
pretty easy to see in the math why. For single channel it's just:
255 - (255 - data + data)

**To Reproduce**
1. rgb a single channel image, note that it works
2. cmy that same image and note that it gives you all zeros

**Expected behavior**
check if something is single channel and leave it be in cmy conversion if so

**Comment by David-Baddeley** [comment]
This looks like it should be fixed
