### ISSUE TITLE
[BUG] recipe text in PYMEVis recipe tab doesn't update

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#498]
**Describe the bug**
As things are added to the PYMEVis recipe through gui clicks, the PYMEVis recipe text doesn't necessarily update. Hitting `Apply Text Changes` resets the pipeline recipe to wherever it last updated (for me, the default modules on load). The pipeline recipe is in fact reset to whatever is in the text, however sometimes the pipeline view can get pretty botched (randomly sorted, a module missing, etc.)

![image](https://user-images.githubusercontent.com/31105780/95528037-fedb3f00-09a4-11eb-910c-5f715e0453f3.png)

**To Reproduce**
1. PYMEVis
2. do, e.g., a multiview correction from the GUI (I hit this while getting a feeling for what's going on in #493 )
3. Open the recipe tab
4. Observe there is/are more recipe module(s) in the display than in the text.
![image](https://user-images.githubusercontent.com/31105780/95528134-42ce4400-09a5-11eb-895e-beadf502e19e.png)
5. Hit `Apply Text Changes`
6. (maybe) Look at the pipeline recipe view

**Expected behavior**
recipe text should stay in sync with both graphical displays

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: [e.g. Win10] ubuntu 16.04
 - Python version: 3.6
 - numpy version: 1.16
 - wxpython version [if a UI bug]: 4.0.4

**Additional context**
probably updating the recipe text is the bigger issue, but pipeline view might be worth following up on too (I've only hit that one time, and while intentionally trying to retrigger several evaluations while looking at another bug)

**Comment by David-Baddeley** [comment]
Tentative fix in #499 . 

I think the pipeline view issues arise when there is an unhandled error somewhere when changing and re-running the pipeline.

Longer term we should also look at whether it's possible to update the recipe incrementally from the text (rather than starting from scratch)
