### ISSUE TITLE
[BUG] coalescing averages (and does not sum) nPhotons

### ISSUE THREAD

**Issue by csoeller** [python-microscopy/python-microscopy#564]
**Describe the bug**

Coalescing currently averages the `nPhotons` property, rather than summing it. Admittedly, only some fitfactories will produce this property, Gaussian 2D prominently does I believe.

**To Reproduce**
1. Open series with 2D Gaussian fitted events in VisGUI
2. Do `Corrections>Chaining` etc to coalesce events
3. check `nPhotons` property if present, pre- and post coalescing
4. Be disappointed...

**Expected behavior**

It seems to me that the `nPhotons` property needs special casing to sum if present.

**Screenshots**

![Screenshot 2020-11-02 at 13 16 42](https://user-images.githubusercontent.com/3750860/97872454-f78e2380-1d0d-11eb-89a8-b47fe3ba8261.png)

![Screenshot 2020-11-02 at 13 16 50](https://user-images.githubusercontent.com/3750860/97872480-01178b80-1d0e-11eb-93ca-3f2c749091f8.png)

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: macOS
 - Python version: 2.7
 - numpy version: 1.16.6
 - wxpython version [if a UI bug]: NA

**Additional context**
Code from latest githgub as of writing.

**Comment by barentine** [comment]
Thanks for catching that @csoeller. If you're in a rush and need to crunch something you can give #565 a shot

**Comment by csoeller** [comment]
Excellent, thanks @barentine for that very quick response. Only became apparent when discussing histograms for a PhD thesis today! I suppose we can close as soon as the #565 is merged.

**Comment by csoeller** [comment]
Fixed with #565.
