### ISSUE TITLE
[BUG] Datasources disappear if you mess up parameters in your recipe

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#631]
**Describe the bug**
If you screw up parameters in your recipe so that one of your outputs returns 0 points, the datasources after this will disappear. You won't know what the problem is until you switch to the `Pipeline Recipe` tab.

![image](https://user-images.githubusercontent.com/1263313/99891402-b5cf0980-2c37-11eb-942a-b112731bbe9c.png)

**Expected behavior**
- Datasource stay selectable in Data pipeline output, but return no points
- There's a red box around the module in the Data pipeline view as well as the Pipeline recipe view

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: macOS 10.15.7
 - Python version: 3.6.10
 - numpy version: 1.16.6
 - wxpython version [if a UI bug]: 4.0.4

**Comment by David-Baddeley** [comment]
I'd argue that the datasources disappearing is the correct behaviour - they are not present if the pipeline doesn't execute. 

Adding a red box in the vertical view and /or greying out the data that is not present in a pipeline in both recipe views would be desirable.

**Comment by David-Baddeley** [comment]
This falls into the general 'making recipes easier to debug' section of the roadmap.
