### ISSUE TITLE
[BUG] glCanvas doesn't refresh after changing selectedDataSource

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#632]
**Describe the bug**
If you change the selected data source under Data pipeline output, you need to then change a layer property as well to get the canvas to refresh.

**To Reproduce**

![image](https://user-images.githubusercontent.com/1263313/99891488-3857c900-2c38-11eb-926e-f8a24ec395a3.png)

![image](https://user-images.githubusercontent.com/1263313/99891492-44438b00-2c38-11eb-85a6-e9b4cefcc281.png)

![image](https://user-images.githubusercontent.com/1263313/99891499-53c2d400-2c38-11eb-875f-b9dae7f01b91.png)

**Expected behavior**
glCanvas should refresh when `selectedDataSource` changes

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: macOS 10.15.7
 - Python version: 3.6.10
 - numpy version: 1.16.6
 - wxpython version [if a UI bug]: 4.0.4

**Additional context**

**Comment by David-Baddeley** [comment]
NOTE- only when the column / point colour you have selected is not in the new datasource.

**Comment by zacsimile** [comment]
Maybe we can add a check when you change datasource that flips the colouring to a valid parameter (e.g. `z` or `t`) if the previous data source `vertexColour` isn't found.

**Comment by zacsimile** [comment]
Hmm, I just tried to recreate this issue and the Colour selection automatically adjusted. Did you fix this @David-Baddeley?

**Comment by David-Baddeley** [comment]
Not that I'm aware of
