### ISSUE TITLE
saving multicolor ImageStacks as h5 drops a color channel

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#64]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/64) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Saving multicolor ImageStacks as tif's is functional, however the 0th color channel is the only one that gets saved when saving h5 (either from the menu -> save as, or from the shell, ImageStack.Save('[something].h5')

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

I'm going to call this a missing feature, rather than a bug. For most use cases, OME TIFF is a better choice for multicolour stacks. To support multicolour stacks in .h5 would require quite a fundamental re-think of how we store images in HDF (not a bad idea in the long run, but not a pressing concern).

We should probably disable the export as HDF option for multi-colour images (or display a warning), however.

**Comment by barentine** [comment]
I don't actually have permission to close this one @David-Baddeley , but it's all set. Thanks!
