### ISSUE TITLE
dh5view saving events in wrong format when saving to h5 (or h5 events loading has regressed?)

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#67]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/67) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Healthy events file from a series opened in dh5view (from the cluster):

```
#!python
>>> image.events
array([('StartAq', 0.010036691729323, '5'),
       ('ProtocolFocus', 0.010036691729323, '5, 54.742'),

```

and opening the new h5 in dh5view after using "save as":

```
#!python
>>> image.events
array([ ('StartAq\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xcdY\xe6\xf5\x1d\x8e\x84?5', '', 0.0),
       ('ProtocolFocus\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xcdY\xe6\xf5\x1d\x8e\x84?5, 54.742', '', 0.0),

```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

h5 -> h5 event loading and saving works fine, haven't tried replicating with cluster data yet, but can't see any obvious issues in the code. It looks like it might be a pytables / HDF peculiarity (maybe related to column order) - what version of pytables are you useing ans on which platform?

**Comment by barentine** [comment]
Been awhile but I just hit this again. Fresh pcs series from the cluster with events, saved it to h5 on local, opened it up and
```
image.events
array([(b'PiezoOnTarget\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>\xbaP\xcdg\xe4\xd7A48.757', b'', 0.),
       (b'StartAq\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00HnQ\xcdg\xe4\xd7A0', b'', 0.),
       (b'ProtocolFocus\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"\x1eb\xcdg\xe4\xd7A0, 48.775', b'', 0.),
       ...,
       (b'PiezoOnTarget\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xd7\x88\xd7zh\xe4\xd7A55.981', b'', 0.),
       (b'StartAq\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf2\xb9\xd7zh\xe4\xd7A2812', b'', 0.),
       (b'ProtocolTask\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xdf\xd1\xe9zh\xe4\xd7AturnAllLasersOff, ', b'', 0.)],
      dtype=[('EventDescr', 'S256'), ('EventName', 'S32'), ('Time', '<f8')])
```

```
(base) smeagol@smeagol:~$ conda list | grep pytables
pytables                  3.6.1            py36h71ec239_0    anaconda
(base) smeagol@smeagol:~$ conda list | grep hdf5
hdf5                      1.10.4               hb1b8bf9_0    anaconda
```

**Comment by barentine** [comment]
still hitting this. Will maybe look later today

**Comment by adrianhollow** [comment]
Same here, after loading ImageStack from h5 with ModuleCollection.loadInput.
```
recipe = ModuleCollection()
recipe.loadInput(path)
print(recipe.namespace['input'].events)
[(b'PiezoOnTarget\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00{J\xed\x9e\x02\x0b\xd8A48.806', b'', 0.)
 (b'StartAq\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00B,\xf3\x9e\x02\x0b\xd8A0', b'', 0.)
 (b'PiezoOnTarget\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00f\x11\xf4\x9e\x02\x0b\xd8A48.803', b'', 0.)
 ...
 (b'StartAq\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00K\xc7\x9b\x8e\x06\x0b\xd8A65670', b'', 0.)
 (b'PiezoOnTarget\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00t\x97\x9e\x8e\x06\x0b\xd8A51.673', b'', 0.)
 (b'ProtocolTask\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00#&\xa1\x8e\x06\x0b\xd8AturnAllLasersOff, ', b'', 0.)]
```
I noticed this while trying to convert this ImageStack to an ImagePyramid with Supertile. Followed the error here:
```
  File "/home/tphan/python-microscopy/PYME/recipes/supertile.py", line 120, in execute
    x, y = tile_pyramid.get_position_from_events(stack.events, stack.mdh)
  File "/home/tphan/python-microscopy/PYME/Analysis/tile_pyramid.py", line 559, in get_position_from_events
    xm = piecewiseMapping.GeneratePMFromEventList(events, mdh, mdh['StartTime'], x0, b'ScannerXPos', 0)
  File "/home/tphan/python-microscopy/PYME/Analysis/piecewiseMapping.py", line 210, in GeneratePMFromEventList
    for e in events[events['EventName'] == eventName]:
```
This does not throw an error, but causes one later on because this loop is never run. Not sure if this is new, but also saw the following while debug-printing:
```
print(events['EventName'])
[b'' b'' b'' ... b'' b'' b'']
```

**Comment by barentine** [comment]
can recreate in simulated PYMEAcquire + clusterofone on macosx
![Screen Shot 2021-02-23 at 10 06 41 AM](https://user-images.githubusercontent.com/31105780/108863152-e6b83500-75be-11eb-861a-f877779d4826.png)
![Screen Shot 2021-02-23 at 10 06 30 AM](https://user-images.githubusercontent.com/31105780/108863164-e881f880-75be-11eb-9a03-824c438c1c8d.png)
[Archive.zip](https://github.com/python-microscopy/python-microscopy/files/6029743/Archive.zip)

**Comment by adrianhollow** [comment]
Couldn't reproduce error as described by @barentine on ubuntu 20, but maybe missing some detail
![Screenshot from 2021-02-24 16-47-43](https://user-images.githubusercontent.com/43847198/109026560-29ae0180-76c0-11eb-908b-523869f8d3d4.png)
![Screenshot from 2021-02-24 16-48-06](https://user-images.githubusercontent.com/43847198/109026563-2a469800-76c0-11eb-9512-162d802f8e31.png)
[24_2_series_A.zip](https://github.com/python-microscopy/python-microscopy/files/6037169/24_2_series_A.zip)

**Comment by barentine** [comment]
looks like you spooled to h5 @adrianhollow. Try unchecking the 'spool to h5 on cluster (cluster of one)` on the right to spool to pzf/pcs

**Comment by adrianhollow** [comment]
I see, yes I just recreated the error

**Comment by adrianhollow** [comment]
Apparently PyTables sorts column keys when creating tables which is why things get hairy. A table is created for events with keys `['EventName', 'Time', 'EventDescr']`, but after sorting the table expects columns in sorted key format `['EventDescr', 'EventName', 'Time']`. You can verify this by calling `image.events['EventDescr']` which will return what we would expect in `image.events['EventName']` and the formating gets awry because event data is converted to the wrong column formats.
@David-Baddeley @barentine , the sequence of `SpoolEvent.column.items()` is broken up in table creation [here](https://github.com/python-microscopy/python-microscopy/blob/174ecc5a8dc309a8559f111a4900d7d46f09b55e/PYME/IO/dataExporter.py#L155). I can manually add a sorting step before `outEvents.append(events)` is called, but maybe it's better to sort the event columns while the events are generated (where?).
![Screenshot from 2021-02-25 16-17-09](https://user-images.githubusercontent.com/43847198/109174368-144edb00-7785-11eb-8952-287f468be37c.png)
Note that dtype is different for the columns which explains the weird string representation. For test purposes, I removed the sorting in `tables.Description.__init__` and everything seemed fine to me.

**Comment by barentine** [comment]
Good find @adrianhollow . If you want a look at a PR which will likely not get merged (doubt @David-Baddeley wants to mess with bytes vs not for event names at the moment, very understandably), but deals with creating events files in a consistent order, you can take a look and repurpose parts of https://github.com/python-microscopy/python-microscopy/pull/161/files for a new PR

**Comment by David-Baddeley** [comment]
On some level this is a pytables error (not checking that the dtypes match on append, and co-ercing into a non-matching dtype instead).

I think the fix might be more complex than needed however - ultimately we should not be sensitive to ordering, either reading or writing as we always index by column name. Rather than trying to fix the ordering (which is likely to be a bit fragile, and shouldn't be needed), it's probably better to just to write the events in the column-order we find them (as we do for localisations and in h5rfile). i.e. modifying `H5Exporter` as follows, replacing:

```python
outEvents = h5out.create_table(h5out.root, 'Events', SpoolEvent,filters=tables.Filters(complevel=5, shuffle=True))

if not events is None:
    #copy events to results file
    if len(events) > 0:
        outEvents.append(events)
```

with

```python
if (events is not None) and (len(events) > 0):
    # we have events, write them
    # sanity check to make sure that we have the correct columns
    assert(sorted(pipeline.events.dtype.names) == ['EventDescr', 'EventName', 'Time'])
    outEvents = h5out.create_table(h5out.root, 'Events', events,filters=tables.Filters(complevel=5, shuffle=True))
else:
    # create empty events table
    outEvents = h5out.create_table(h5out.root, 'Events', SpoolEvent,filters=tables.Filters(complevel=5, shuffle=True))
```

**Comment by adrianhollow** [comment]
Turns out that as long as the events are a numpy array, the sorting will be done implicitly without any further overhead. This means the suggested assert is unnecessary because pytables will sort the columns under the hood while preserving key-value mapping. But I've added another assert to make sure events is a numpy array, otherwise we'll be back to square one.

**Comment by David-Baddeley** [comment]
The `assert` I put in sorts the names before checking, so is not checking order.  It's more a paranoid sanity check in case someone else is generating events and trying to save them to ensure that any saved events will be readable.

**Comment by barentine** [comment]
Sounds like #904 is ready then? Sanity checks / paranoia around events is very welcome in my eyes

**Comment by barentine** [comment]
i think this can close now, but you'll have to do it @David-Baddeley
