### ISSUE TITLE
[ENHANCEMENT] Make default load/save folder match most recently opened file

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#704]
**Is your feature request related to a problem? Please describe.**
I often wish that `pymevis` File>Open and File>Save (and `pymeimage` File>Save for rendered images) defaulted to the folder of the most recently opened file instead of to the last place I saved a file.

**Comment by David-Baddeley** [comment]
- Hmm, this might well be OS dependant, as I think we follow the OS defaults here. 

- Manually over-riding sounds like a lot of work and could incur maintenance overhead we don't really want. 

- There are also arguments both ways as to what should be the default - I like to keep a pretty hard separation between raw data and analysis / processed data, which makes the "Save to last place I saved" behaviour preferable to "Save to last place I opened" for me. I suspect it's not possible to have a default here that works for everyone.

@zacsimile - unless you have strong feelings about this, I'll mark as won't fix and/or close.
