### ISSUE TITLE
File --> Close does not work to close dh5view. [BUG]

### ISSUE THREAD

**Issue by mdlessard75** [python-microscopy/python-microscopy#731]
**Describe the bug**
Using the Close function, under File, in dh5view, does not do anything when only one panel is open.

**To Reproduce**
1. Go to File
2. Click on Close

**Expected behavior**
I would expect the panel to close.

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: Win10 64
 - Python version: 3.7.9
 - numpy version: 1.19.2
 - wxpython version [if a UI bug]: 4.0.4

**Comment by David-Baddeley** [comment]
I think this is a hangover from a super old (<3.x) wx version where default actions were automatically bound if you added menu items with specific IDs (e.g. wx.ID_CLOSE). Fix coming shortly ...
