### ISSUE TITLE
[BUG] PYMEVis side-view buttons inverts z

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#763]
**Describe the bug**

https://user-images.githubusercontent.com/31105780/104079656-4666a680-51f2-11eb-8715-31e01d14082c.mp4

clicking the side views shows from the right lateral angle, but flips z

also note that if you have 2D selected and click one of the side views it doesn't just switch to 3D and go to the angle, which would be kinda nice.

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: osx 10.15
 - Python version: 3.7
 - numpy version: 1.19
 - wxpython version [if a UI bug]: 4.0.4

**Comment by David-Baddeley** [comment]
This is probably a hang-over from when we flipped the y-axis so that it matches the direction in images.
