### ISSUE TITLE
[BUG] PYME.LMVis.gl_render3D_shaders.LMGLShaderCanvas.getIm() returns bad snapshot for meshes

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#765]
This makes it difficult to produce mesh animations that look good.

**Screenshot on my mac**

![image](https://user-images.githubusercontent.com/1263313/104094062-a85bf600-525c-11eb-8441-6fd829bfd1b9.png)

**getIm() result of the same view**

![mesh_snap](https://user-images.githubusercontent.com/1263313/104094073-b6aa1200-525c-11eb-99cf-88f359abb218.png)

**Comment by David-Baddeley** [comment]
I suspect that depth checking is not working as we don't seem to attach a depth-buffer for the offscreen rendering. By the look of things, we also don't do anti-aliasing (which will make the images more jagged). Will see if it's easy to fix ... 

See also:
https://stackoverflow.com/questions/5751081/how-to-use-depth-testing-when-rendering-to-an-offscreen-buffer-then-onto-texture

**Comment by David-Baddeley** [comment]
Immediate issue fixed in #771

![image](https://user-images.githubusercontent.com/19475296/104247410-a26c4c00-54cc-11eb-8a37-9b71a6d9b987.png)

Images are still a little more pixilated due to lack of multi-sampling / antialiasing.

**Comment by David-Baddeley** [comment]
![image](https://user-images.githubusercontent.com/19475296/104250096-bebeb780-54d1-11eb-9652-fa0a5b7136b6.png)

now with antialising :)

**Comment by zacsimile** [comment]
Very cool! Thank you, @David-Baddeley!

**Comment by David-Baddeley** [comment]
Transparency also works (I was a rather worried that it wouldn't due to the two-pass rendering approach).
