### ISSUE TITLE
wx import in code which may be called by cluster

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#79]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/79) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

A couple of imports make some recipes fail on the cluster due to wx imports in:
- LMVis.dataExporter (used in image output recipe modules)
- LMVis.pipeline (indirectly due to ```from PYME.LMVis.triBlobs import BlobSettings```; used in recipes.localisations.Pipelineify)

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Hmm - what is the failure message? Although undesirable, you should still be able to import wx in console programs (even on OSX where you need to dodge framework issues - these manifest when you actually try and create a wxApp).

Fixes are unfortunately not completely straightforward.

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

```python
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/PYME/recipes/output.py", line 200, in save
    v.Save(out_filename)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/PYME/IO/image.py", line 1008, in Save
    from PYME.IO import dataExporter
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/PYME/IO/dataExporter.py", line 25, in <module>
    import wx
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/wx-3.0-gtk2/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

‌

I should be able to install libgtk 2.0 \(`apt-get install libgtk2.0-0`, will need to do confirm later this week\) though it would be nice if this was installed as a part of the wx installation. I think we are probably safe to simply resolve this issue, since I would expect anyone setting up a cluster on a desktop linux distro to be able to take care of it.

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Looks like they may have depreciated/dropped that library in the default ubuntu 18.04 install. [https://askubuntu.com/questions/1085282/missing-libgtk-x11-2-0-so-0-in-18-04](https://askubuntu.com/questions/1085282/missing-libgtk-x11-2-0-so-0-in-18-04)

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Installed fine with a simple apt-get install on 18.04 server for me …

**Comment by zacsimile** [comment]
Is this still an issue? Do we use `wx3` anymore?

**Comment by David-Baddeley** [comment]
wx3 is still our officially supported version, that said, this is easily resolved by installing the wx libraries. Can probably close - at this stage it's more a part of the UI/logic separation super-issue.
