### ISSUE TITLE
wxWidgets Debug Alert on every VisGUI close after opening h5r

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#82]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/82) by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

A wxWidgets Debug Alert shows up every time VisGUI is closed on Windows if I’ve opened an h5r during that session. It doesn’t affect anything, it would just be nice if VisGUI exited quietly.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

I’ve noticed that too - currently no idea what is causing it. Seems to be windows specific.

**Comment by David-Baddeley** [comment]
**Original comment by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

As best I can tell from Google, this issue is fixed in later versions of wx. Most people recommend switching to the Python 3 version of wx to fix this.

**Comment by zacsimile** [comment]
This has gone away as we've upgraded `wx` and switched to Python 3. I think we can close.

**Comment by David-Baddeley** [comment]
I'll mark it as 'wontfix' - it's still a bug for now as py2.7 wx3 is still our officially supported config, although our upgrade path will give us a way out in the medium term.
