### ISSUE TITLE
[BUG] Spheres display method not working.

### ISSUE THREAD

**Issue by lukasfue** [python-microscopy/python-microscopy#829]
**Describe the bug**
Using point display method "spheres" does not work. I do not recieve a traceback for it, the points just disappear when I switch to spheres. Switching to another method, such as pointsprites, works fine.

**To Reproduce**
1. Load data
2. Display data as spheres
3. See that they disappear.

**Expected behavior**
Points are displayed as spheres.

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
python-microscopy=20.10.05
python=3.7.9, platform=win32
numpy=1.19.1, wx=4.0.4 msw (phoenix) wxWidgets 3.0.5

**Comment by David-Baddeley** [comment]
Probably related to #98

It does work correctly on OSX. Presumably some quirk of the underlying OpenGL implementations.

**Comment by David-Baddeley** [comment]
Could possibly be display driver / graphics card dependant

**Comment by zacsimile** [comment]
I wonder if there's like a single GL call we use that only works on macs for some reason. There's a couple of platform-specific functions. Could also be different system GL versions.

Sorry if this was reiterating what you'd already said, @David-Baddeley. I was thinking out loud.

**Comment by zacsimile** [comment]
Funny enough my mac has OpenGL 2.1 and my work Windows has OpenGL 1.1 so I'm thinking that might be it. Can @David-Baddeley or @barentine check their Linux OpenGL version with `glxinfo | grep "OpenGL version"`?

**Comment by David-Baddeley** [comment]
going to be optimistic and close this .... would be good if someone could test on linux.
