### ISSUE TITLE
refactor surface /spherical harmonic fitting

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#83]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/83) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Assuming PR [#269](https://bitbucket.org/david_baddeley/python-microscopy/pull-requests/269/adding-recipe-module-for-quadratic-patch)  is merged in a similar form to it’s current state, I would propose:

* move spherical harmonic recipe modules from PYME/recipes/localisations.py into PYME/recipes/surface\_fitting.py
* move spherical harmonic gui stuff into LMVis/Extras/surface\_fitting.py and the “Analysis>surface fitting” drop-down menu.
* I submit a PR to add in the spherical harmonic unit-tests and principal-axes scaling I have in [https://github.com/bewersdorflab/nucleus-analysis](https://github.com/bewersdorflab/nucleus-analysis)

**Comment by zacsimile** [comment]
I think this is addressed in #197.

**Comment by zacsimile** [comment]
I think this can be closed.

**Comment by barentine** [comment]
agreed - this can be closed

**Comment by zacsimile** [comment]
@David-Baddeley can you close this issue?
