### ISSUE TITLE
[BUG] Recipe editor mouse target doesn't understand layers, focus not set

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#834]
**Describe the bug**
I add a `FilterTable` to my recipe, I double click it, open the filter dialog, right click and hit `Add` (we should have an `Add` button so this is clearer). If there's another tile behind `Add`, the dialog for that tile opens as well when I press `Add`, presumably due to a mouse pointer target checking operation that doesn't understand layers. Clearly the focus is still on the recipe editor window. If this wasn't annoying enough, when I close the new dialog it re-reuns the recipe, so I'm left sitting there for a few seconds before I can use the dialog I wanted.

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: macOS 10.15.7
 - Python version: 3.7.9
 - numpy version: 1.19.2
 - wxpython version [if a UI bug]: 4.0.4

**Comment by barentine** [comment]
sounds like the same issue in #832

**Comment by zacsimile** [comment]
Moved conversation to #832.
