### ISSUE TITLE
[ENHANCEMENT] Don't collapse every un-pinned pane when I open a collapsed pane

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#837]
Proportionally resize instead. For example,

![image](https://user-images.githubusercontent.com/1263313/107525602-009c5580-6b85-11eb-8915-33dc2af18df6.png)

And then I open Output Filter

![image](https://user-images.githubusercontent.com/1263313/107525637-098d2700-6b85-11eb-8aa5-b4ef7228ff25.png)

There was plenty of space to expand output filter while keeping Layers up. Even if part of layers gets hidden, that would be preferable to them disappearing entirely.

**Comment by David-Baddeley** [comment]
This is related to how the layer pane is sized (max possible layer size), also probably (in terms of solution) a duplicate of #836

**Comment by David-Baddeley** [comment]
Also, partially hidden doesn't work for a number of reasons - not least how do you re-show /access the hidden bits. I think it has to be all or nothing.

**Comment by zacsimile** [comment]
I guess I'm advocating for partially hidden + a scroll bar in each pane. As you mention in #836, this might be tricky, though.

**Comment by zacsimile** [comment]
Another option would be arbitrary docking/resizing of the different panes, a la Adobe products.

**Comment by zacsimile** [comment]
I'm going to close this as I agree this entire conversation belongs in #836.
