### ISSUE TITLE
[BUG] Don't run recipes if I hit cancel

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#838]
If I click on a recipe tile in the `Pipeline Recipe` tab in `PYMEVis` and the dialog pops up and then I hit cancel, the recipe re-runs. This shouldn't happen.

**Comment by David-Baddeley** [comment]
Which traits / traitsui version? This smells a little like a traits error.

**Comment by David-Baddeley** [comment]
Actually, there is no way of robustly handling a cancel - traits are updated as you edit them. This makes cancel functionally equivalent to OK. Have removed the cancel button as it was confusing.

**Comment by David-Baddeley** [comment]
PS - I assume it only runs if you have changed a parameter

**Comment by zacsimile** [comment]
It runs even if I don’t change a parameter. If I just hit cancel, it runs.

**Comment by David-Baddeley** [comment]
That's odd, as it should check if new_params==old_params and only run if they are different.

**Comment by David-Baddeley** [comment]
see `ModuleBase.edit_no_invalidate()`

**Comment by zacsimile** [comment]
You sufficiently convinced me to try again. I even add a print statement "Executing..." to a few of the `execute()` commands in some recipes (e.g. DBSCAN). If I click and then hit cancel, I get the print statement, even if I change no parameters.

**Comment by David-Baddeley** [comment]
I've found the bug here which is making things execute when they shouldn't. Fix to follow (probably the *real* fix to this issue - I might have closed prematurely)

**Comment by zacsimile** [comment]
Thanks for pushing on this, @David-Baddeley!
