### ISSUE TITLE
[discussion] does psfExtraction `Tag Points` do anything?

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#859]
**What are you trying to do?**
be lazy and not `Tag` each of my beads
**Where are you stuck?**
nothing happens and i haven't looked at the code yet

**Comment by David-Baddeley** [comment]
Yep, although you need to use the `blobFinding` module first to detect the beads.

1) load the `blobFinding` and `psfExtraction` modules
2) use the `Find` button in the `ObjectFinding` module 
    
![image](https://user-images.githubusercontent.com/19475296/108165784-0206e880-7158-11eb-8f6d-6357f9d323f7.png)

3) use `Tag Points` to automatically tag all of the found beads

**Comment by David-Baddeley** [comment]
@barentine - can we close this? 

Alternatively, put it on the docs TODO

**Comment by barentine** [comment]
Sounds good

**Comment by barentine** [comment]
Thanks David
