### ISSUE TITLE
dh5view slice-length display inconsistent

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#86]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/86) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

The display at the bottom of dh5view for a 190-frame series is “0 / 190”, which should really be “0 / 189” or “1 / 190”. This used to throw the Traceback below on earlier versions of PYME when you loop through playback \(maybe still does\), but in this instance I used the go-to button and mistakenly entered 190, which is of course an invalid index in Python for a 190-long series:

```
Traceback (most recent call last):
  File &amp;#34;/Users/Andrew/python-microscopy/PYME/DSView/scrolledImagePanel.py&amp;#34;, line 58, in OnPaint
    self.renderer(MemDC);
  File &amp;#34;/Users/Andrew/python-microscopy/PYME/DSView/arrayViewPanel.py&amp;#34;, line 495, in DoPaint
    im = self.Render(fullImage)
  File &amp;#34;/Users/Andrew/python-microscopy/PYME/DSView/arrayViewPanel.py&amp;#34;, line 1107, in Render
    seg = self.do.ds[x0_:(x0_+sX_):step,y0_:(y0_+sY_):step,int(self.do.zp), chan].squeeze().T
  File &amp;#34;/Users/Andrew/python-microscopy/PYME/IO/DataSources/BaseDataSource.py&amp;#34;, line 104, in __getitem__
    r = np.concatenate([np.atleast_2d(self.getSlice(i)[keys[0], keys[1]])[:,:,None] for i in range(*keys[2].indices(self.getNumSlices()))], 2)
ValueError: need at least one array to concatenate
```

‌

Hopefully this screen capture, at the bottom with “Slice No:”, shows the zero-/one-index inconsistency.

![](https://bitbucket.org/repo/kAoqj6/images/2588221697-Screen%20Shot%202019-08-21%20at%208.30.08%20AM.png)

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

I need a little more info here … I’m not sure I understand what the title means \(or more generally how to reproduce this\). Are you trying to say that indexing out of bounds generates a value error rather than an index error?

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Tried to update the description, @{557058:8eeba2ee-49a0-499e-941c-77745cfc22b9} . Sorry it was so sparse!

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Hmm - I think saying frame 0 of 190 \(or frame 189 of 190\) is fine. I think changing it to frame x of \(N-1\) would be wrong, as there are N frames, not N-1 frames. To me it’s common sense that if you start indexing at 0, 189 would be the maximum index for something with a size of 190, but perhaps I’ve been around computers too long. In terms of UI I think there are two logically consistent options for displaying frame numbers - as is, or 1-based indexing. 1 based is probably slightly more intuitive for the non-mathematically / non-programming inclined, but runs into issues once you switch to the console to do something and have to change your indexing. For this reason I’d argue for keeping the status quo.

In any case, I’ve now fixed the code in that you can’t set a value that is out of bounds - I haven’t changed the display logic, but have fixed the clipping and added more informative error messages if you try and set things out of bounds. This should hopefully be good enough to address any usability concerns.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Can no longer set index out of bounds, so partially fixed. 

Won't change indexing to maintain compatibility with numpy indexing in console.

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

I think the partial fix may be what’s stopping playback from looping.

```
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/ui/mytimer.py", line 39, in Notify
    a()
  File "/home/smeagol/code/python-microscopy/PYME/DSView/modules/playback.py", line 124, in OnFrame
    self.do.zp +=1
  File "/home/smeagol/code/python-microscopy/PYME/DSView/displayOptions.py", line 117, in zp
    raise IndexError('Z position out of bounds')
IndexError: Z position out of bounds
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/ui/mytimer.py", line 39, in Notify
    a()
  File "/home/smeagol/code/python-microscopy/PYME/DSView/modules/playback.py", line 124, in OnFrame
    self.do.zp +=1
  File "/home/smeagol/code/python-microscopy/PYME/DSView/displayOptions.py", line 117, in zp
    raise IndexError('Z position out of bounds')
IndexError: Z position out of bounds
```

My preference would be to display 0/189 - my feelings about the current status quo is that it’s wrong for both 0- and 1-indexing, which is more confusing than picking either of the others.

**Comment by barentine** [comment]
I'm not sure why this is closed. The 'partial fix' prevents looping playback in dh5view and is kind of embarrassing
