### ISSUE TITLE
[ENHANCEMENT] Automatically select text in editable boxes when I hit tab

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#890]
For example, if I use the hist limits editor and open the bounds, I want to edit them. It would be nice if when I hit tab the bound number was selected so I just have to type a number to edit it, rather than selecting it first.

Currently this:
![image](https://user-images.githubusercontent.com/1263313/109018301-fbabcb80-7685-11eb-9b42-6efda6577f73.png)

Want this:
![image](https://user-images.githubusercontent.com/1263313/109018350-09615100-7686-11eb-979a-bf62854eb4ea.png)

**Comment by David-Baddeley** [comment]
I suspect is going to be pretty hard to do without hacking each and every text control (you'd need to handle `wx.EVT_SET_FOCUS` on the control and select the text in the handler). A quick google suggests that there might be timing issues with this and you'd need to either send yourself another event, or use, e.g. `wx.CallAfter` to actually set the selection.

**Comment by David-Baddeley** [comment]
We could potentially subclass `wx.TextCtrl` and replace all our hard-coded uses, but traits etc ... would still use the native control.

**Comment by zacsimile** [comment]
I figured. I just wanted to put this down as something that would be nice to have in case we ever get around to it. Definitely low, low priority.

**Comment by David-Baddeley** [comment]
Just added the won't fix label, as I don't see any clean way of doing it - particularly not in a cross-platform manner.
