### ISSUE TITLE
arrayViewPanel.GrabPNGToBuffer broken on Py3, pillow6, wx4

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#93]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/93) by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Below copied from generic py3 thread …

‌

The current `arrayViewPanel.GrabPNGToBuffer` function is broken on py3, pillow 6.0.0, wx 4.0.4, because the `PIL.Image.frombytes` takes a bytes-like object and the `wx.Bitmap.ConvertToImage()` returns a byte-array.

In theory, where `out` is a `BytesIO` instance, either `img.ConvertToImage().SaveFile(out, wx.BITMAP_TYPE_PNG)` or `wx.PNGHandler().SaveFile(img.ConvertToImage(), out)` should allow us to skip PIL altogether, but in the jinja-templated html I get a `Failed to load resource: net::ERR_INVALID_URL`with the url starting with: **data:image/png;base64,b'iVBORw0KGgoAAAANSUhEUgAABAAAAAQACAIAAADwf7zUAAAAA3NCSVQICAjb4U/gAAAgAElEQVR4nOy9e3Bb2X0meC4BXIAA8X7oggAJEOBDhESpJbFbUrda3eN2t93d3nGl42Sy2Ue5PDuZnWQy2UklO\+vUJKVKUpNUZuJknWSSbE28lTj2rJPYSbbsJGO3H612d0vtlvWgJEp8QCIJkAABEsAF8cYF9o/POHuEx8XFg2qnqn9/sEDgvO45557z/d4cq**

I’ve tried doing the base64 encoding of the image before templating and removing that bit from the template, but this of course yields the same result.

‌

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

The problem will be with the b' \(or potentially just the b at the start of the base64 encoded string. Probably solvable by decoding ing the output of base64encode before passing to the template.

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Will give that a shot. Will also leave the original traceback here for completeness

‌

```
Traceback (most recent call last):
  File "/Users/Andrew/code/nep-fitting/nep_fitting/dsviewer_modules/sted_psf_fitting.py", line 172, in <lambda>
    ensemble_test_btn.Bind(wx.EVT_BUTTON, lambda e: self._on_ensemble_test())
  File "/Users/Andrew/code/nep-fitting/nep_fitting/dsviewer_modules/sted_psf_fitting.py", line 361, in _on_ensemble_test
    context['img_data'] = self._dsviewer.view.GrabPNGToBuffer()
  File "/Users/Andrew/python-microscopy/PYME/DSView/arrayViewPanel.py", line 561, in GrabPNGToBuffer
    im1 = Image.frombytes(mode='RGB', size=tuple(img.GetSize()), data=img.ConvertToImage().GetData())
  File "/Users/Andrew/miniconda3/lib/python3.6/site-packages/PIL/Image.py", line 2542, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/Users/Andrew/miniconda3/lib/python3.6/site-packages/PIL/Image.py", line 826, in frombytes
    s = d.decode(data)
TypeError: argument 1 must be read-only bytes-like object, not bytearray
```

‌

**Comment by barentine** [comment]
We can close this, fixed with c4cdc928deb6c8d6200589f3f1dce689a8929a34

**Comment by barentine** [comment]
bump

**Comment by zacsimile** [comment]
I think we can close this.
