### ISSUE TITLE
VisGUI menu order random on py3/wx4

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#97]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/97) by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Suspect that this is more a wx issue than anything else

**Comment by zacsimile** [comment]
This is due to `glob.glob()` returning files in a random order. Fix shortly.

**Comment by zacsimile** [comment]
This was fixed with #204. I think we can close!
