### ISSUE TITLE
"sphere" mode doesn't work in VisGUI on Linux

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#98]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/98) by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

as per title

py=2.7, wx=4

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

also on py3k

**Comment by David-Baddeley** [comment]
should (hopefully be fixed with #841

**Comment by barentine** [comment]
can confirm the fix works on ubuntu 16.04

**Comment by David-Baddeley** [comment]
great!
