### ISSUE TITLE
Linux, wx4, points layer not automatically created in VisGUI on data load

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#99]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/99) by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Has to do with the view window not having focus and the openGL context not having been created when `add_layer` is called \(error is glCreateProgram failed\). 

‌

‌

**Comment by barentine** [comment]
this is still present

**Comment by David-Baddeley** [comment]
fixed with #1163
